language: node_js

node_js: 
  - "lts/*"

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  # Set up X Virtual Framebuffer because an instance of VS Code runs the tests
  # See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - npm install
  - npm run vscode:prepublish
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash) -s .coverage
