language: node_js

node_js:
    - 'lts/*'

matrix:
    include:
        - os: linux
          dist: bionic
        - os: osx

services:
    - xvfb

script:
    - npm install
    - npm run vscode:prepublish
    - npm test

after_success:
    - test $TRAVIS_BRANCH = "master" && bash <(curl -s https://codecov.io/bash) -s .coverage
