
/**
 * THIS FILE IS AUTOGENERATED BY 'generateServiceClient.ts'.
 * DO NOT EDIT BY HAND.
 */

import {Request} from 'aws-sdk/lib/request';
import {Response} from 'aws-sdk/lib/response';
import {AWSError} from 'aws-sdk/lib/error';
import {Service} from 'aws-sdk/lib/service';
import {ServiceConfigurationOptions} from 'aws-sdk/lib/service';
import {ConfigBase as Config} from 'aws-sdk/lib/config-base';
interface Blob {}
declare class FeatureDevProxyClient extends Service {
  /**
   * Constructs a service object. This object has one method for each API operation.
   */
  constructor(options?: FeatureDevProxyClient.Types.ClientConfiguration)
  config: Config & FeatureDevProxyClient.Types.ClientConfiguration;
  /**
   * 
   */
  createArtifactUploadUrl(params: FeatureDevProxyClient.Types.CreateUploadUrlRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateUploadUrlResponse) => void): Request<FeatureDevProxyClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createArtifactUploadUrl(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateUploadUrlResponse) => void): Request<FeatureDevProxyClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createTaskAssistConversation(params: FeatureDevProxyClient.Types.CreateTaskAssistConversationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateTaskAssistConversationResponse) => void): Request<FeatureDevProxyClient.Types.CreateTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  createTaskAssistConversation(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateTaskAssistConversationResponse) => void): Request<FeatureDevProxyClient.Types.CreateTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  createUploadUrl(params: FeatureDevProxyClient.Types.CreateUploadUrlRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateUploadUrlResponse) => void): Request<FeatureDevProxyClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createUploadUrl(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateUploadUrlResponse) => void): Request<FeatureDevProxyClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createUserMemoryEntry(params: FeatureDevProxyClient.Types.CreateUserMemoryEntryInput, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateUserMemoryEntryOutput) => void): Request<FeatureDevProxyClient.Types.CreateUserMemoryEntryOutput, AWSError>;
  /**
   * 
   */
  createUserMemoryEntry(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateUserMemoryEntryOutput) => void): Request<FeatureDevProxyClient.Types.CreateUserMemoryEntryOutput, AWSError>;
  /**
   * 
   */
  createWorkspace(params: FeatureDevProxyClient.Types.CreateWorkspaceRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateWorkspaceResponse) => void): Request<FeatureDevProxyClient.Types.CreateWorkspaceResponse, AWSError>;
  /**
   * 
   */
  createWorkspace(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.CreateWorkspaceResponse) => void): Request<FeatureDevProxyClient.Types.CreateWorkspaceResponse, AWSError>;
  /**
   * 
   */
  deleteTaskAssistConversation(params: FeatureDevProxyClient.Types.DeleteTaskAssistConversationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.DeleteTaskAssistConversationResponse) => void): Request<FeatureDevProxyClient.Types.DeleteTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  deleteTaskAssistConversation(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.DeleteTaskAssistConversationResponse) => void): Request<FeatureDevProxyClient.Types.DeleteTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  deleteUserMemoryEntry(params: FeatureDevProxyClient.Types.DeleteUserMemoryEntryInput, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.DeleteUserMemoryEntryOutput) => void): Request<FeatureDevProxyClient.Types.DeleteUserMemoryEntryOutput, AWSError>;
  /**
   * 
   */
  deleteUserMemoryEntry(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.DeleteUserMemoryEntryOutput) => void): Request<FeatureDevProxyClient.Types.DeleteUserMemoryEntryOutput, AWSError>;
  /**
   * 
   */
  deleteWorkspace(params: FeatureDevProxyClient.Types.DeleteWorkspaceRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.DeleteWorkspaceResponse) => void): Request<FeatureDevProxyClient.Types.DeleteWorkspaceResponse, AWSError>;
  /**
   * 
   */
  deleteWorkspace(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.DeleteWorkspaceResponse) => void): Request<FeatureDevProxyClient.Types.DeleteWorkspaceResponse, AWSError>;
  /**
   * 
   */
  generateCompletions(params: FeatureDevProxyClient.Types.GenerateCompletionsRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GenerateCompletionsResponse) => void): Request<FeatureDevProxyClient.Types.GenerateCompletionsResponse, AWSError>;
  /**
   * 
   */
  generateCompletions(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GenerateCompletionsResponse) => void): Request<FeatureDevProxyClient.Types.GenerateCompletionsResponse, AWSError>;
  /**
   * 
   */
  getCodeAnalysis(params: FeatureDevProxyClient.Types.GetCodeAnalysisRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetCodeAnalysisResponse) => void): Request<FeatureDevProxyClient.Types.GetCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  getCodeAnalysis(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetCodeAnalysisResponse) => void): Request<FeatureDevProxyClient.Types.GetCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  getCodeFixJob(params: FeatureDevProxyClient.Types.GetCodeFixJobRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetCodeFixJobResponse) => void): Request<FeatureDevProxyClient.Types.GetCodeFixJobResponse, AWSError>;
  /**
   * 
   */
  getCodeFixJob(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetCodeFixJobResponse) => void): Request<FeatureDevProxyClient.Types.GetCodeFixJobResponse, AWSError>;
  /**
   * 
   */
  getTaskAssistCodeGeneration(params: FeatureDevProxyClient.Types.GetTaskAssistCodeGenerationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTaskAssistCodeGenerationResponse) => void): Request<FeatureDevProxyClient.Types.GetTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  getTaskAssistCodeGeneration(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTaskAssistCodeGenerationResponse) => void): Request<FeatureDevProxyClient.Types.GetTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  getTestGeneration(params: FeatureDevProxyClient.Types.GetTestGenerationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTestGenerationResponse) => void): Request<FeatureDevProxyClient.Types.GetTestGenerationResponse, AWSError>;
  /**
   * 
   */
  getTestGeneration(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTestGenerationResponse) => void): Request<FeatureDevProxyClient.Types.GetTestGenerationResponse, AWSError>;
  /**
   * 
   */
  getTransformation(params: FeatureDevProxyClient.Types.GetTransformationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTransformationResponse) => void): Request<FeatureDevProxyClient.Types.GetTransformationResponse, AWSError>;
  /**
   * 
   */
  getTransformation(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTransformationResponse) => void): Request<FeatureDevProxyClient.Types.GetTransformationResponse, AWSError>;
  /**
   * 
   */
  getTransformationPlan(params: FeatureDevProxyClient.Types.GetTransformationPlanRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTransformationPlanResponse) => void): Request<FeatureDevProxyClient.Types.GetTransformationPlanResponse, AWSError>;
  /**
   * 
   */
  getTransformationPlan(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.GetTransformationPlanResponse) => void): Request<FeatureDevProxyClient.Types.GetTransformationPlanResponse, AWSError>;
  /**
   * 
   */
  listAvailableCustomizations(params: FeatureDevProxyClient.Types.ListAvailableCustomizationsRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListAvailableCustomizationsResponse) => void): Request<FeatureDevProxyClient.Types.ListAvailableCustomizationsResponse, AWSError>;
  /**
   * 
   */
  listAvailableCustomizations(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListAvailableCustomizationsResponse) => void): Request<FeatureDevProxyClient.Types.ListAvailableCustomizationsResponse, AWSError>;
  /**
   * 
   */
  listAvailableProfiles(params: FeatureDevProxyClient.Types.ListAvailableProfilesRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListAvailableProfilesResponse) => void): Request<FeatureDevProxyClient.Types.ListAvailableProfilesResponse, AWSError>;
  /**
   * 
   */
  listAvailableProfiles(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListAvailableProfilesResponse) => void): Request<FeatureDevProxyClient.Types.ListAvailableProfilesResponse, AWSError>;
  /**
   * 
   */
  listCodeAnalysisFindings(params: FeatureDevProxyClient.Types.ListCodeAnalysisFindingsRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListCodeAnalysisFindingsResponse) => void): Request<FeatureDevProxyClient.Types.ListCodeAnalysisFindingsResponse, AWSError>;
  /**
   * 
   */
  listCodeAnalysisFindings(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListCodeAnalysisFindingsResponse) => void): Request<FeatureDevProxyClient.Types.ListCodeAnalysisFindingsResponse, AWSError>;
  /**
   * 
   */
  listEvents(params: FeatureDevProxyClient.Types.ListEventsRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListEventsResponse) => void): Request<FeatureDevProxyClient.Types.ListEventsResponse, AWSError>;
  /**
   * 
   */
  listEvents(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListEventsResponse) => void): Request<FeatureDevProxyClient.Types.ListEventsResponse, AWSError>;
  /**
   * 
   */
  listFeatureEvaluations(params: FeatureDevProxyClient.Types.ListFeatureEvaluationsRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListFeatureEvaluationsResponse) => void): Request<FeatureDevProxyClient.Types.ListFeatureEvaluationsResponse, AWSError>;
  /**
   * 
   */
  listFeatureEvaluations(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListFeatureEvaluationsResponse) => void): Request<FeatureDevProxyClient.Types.ListFeatureEvaluationsResponse, AWSError>;
  /**
   * 
   */
  listUserMemoryEntries(params: FeatureDevProxyClient.Types.ListUserMemoryEntriesInput, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListUserMemoryEntriesOutput) => void): Request<FeatureDevProxyClient.Types.ListUserMemoryEntriesOutput, AWSError>;
  /**
   * 
   */
  listUserMemoryEntries(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListUserMemoryEntriesOutput) => void): Request<FeatureDevProxyClient.Types.ListUserMemoryEntriesOutput, AWSError>;
  /**
   * 
   */
  listWorkspaceMetadata(params: FeatureDevProxyClient.Types.ListWorkspaceMetadataRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListWorkspaceMetadataResponse) => void): Request<FeatureDevProxyClient.Types.ListWorkspaceMetadataResponse, AWSError>;
  /**
   * 
   */
  listWorkspaceMetadata(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ListWorkspaceMetadataResponse) => void): Request<FeatureDevProxyClient.Types.ListWorkspaceMetadataResponse, AWSError>;
  /**
   * 
   */
  resumeTransformation(params: FeatureDevProxyClient.Types.ResumeTransformationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ResumeTransformationResponse) => void): Request<FeatureDevProxyClient.Types.ResumeTransformationResponse, AWSError>;
  /**
   * 
   */
  resumeTransformation(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.ResumeTransformationResponse) => void): Request<FeatureDevProxyClient.Types.ResumeTransformationResponse, AWSError>;
  /**
   * 
   */
  sendTelemetryEvent(params: FeatureDevProxyClient.Types.SendTelemetryEventRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.SendTelemetryEventResponse) => void): Request<FeatureDevProxyClient.Types.SendTelemetryEventResponse, AWSError>;
  /**
   * 
   */
  sendTelemetryEvent(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.SendTelemetryEventResponse) => void): Request<FeatureDevProxyClient.Types.SendTelemetryEventResponse, AWSError>;
  /**
   * 
   */
  startCodeAnalysis(params: FeatureDevProxyClient.Types.StartCodeAnalysisRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartCodeAnalysisResponse) => void): Request<FeatureDevProxyClient.Types.StartCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  startCodeAnalysis(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartCodeAnalysisResponse) => void): Request<FeatureDevProxyClient.Types.StartCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  startCodeFixJob(params: FeatureDevProxyClient.Types.StartCodeFixJobRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartCodeFixJobResponse) => void): Request<FeatureDevProxyClient.Types.StartCodeFixJobResponse, AWSError>;
  /**
   * 
   */
  startCodeFixJob(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartCodeFixJobResponse) => void): Request<FeatureDevProxyClient.Types.StartCodeFixJobResponse, AWSError>;
  /**
   * 
   */
  startTaskAssistCodeGeneration(params: FeatureDevProxyClient.Types.StartTaskAssistCodeGenerationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartTaskAssistCodeGenerationResponse) => void): Request<FeatureDevProxyClient.Types.StartTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  startTaskAssistCodeGeneration(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartTaskAssistCodeGenerationResponse) => void): Request<FeatureDevProxyClient.Types.StartTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  startTestGeneration(params: FeatureDevProxyClient.Types.StartTestGenerationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartTestGenerationResponse) => void): Request<FeatureDevProxyClient.Types.StartTestGenerationResponse, AWSError>;
  /**
   * 
   */
  startTestGeneration(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartTestGenerationResponse) => void): Request<FeatureDevProxyClient.Types.StartTestGenerationResponse, AWSError>;
  /**
   * 
   */
  startTransformation(params: FeatureDevProxyClient.Types.StartTransformationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartTransformationResponse) => void): Request<FeatureDevProxyClient.Types.StartTransformationResponse, AWSError>;
  /**
   * 
   */
  startTransformation(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StartTransformationResponse) => void): Request<FeatureDevProxyClient.Types.StartTransformationResponse, AWSError>;
  /**
   * 
   */
  stopTransformation(params: FeatureDevProxyClient.Types.StopTransformationRequest, callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StopTransformationResponse) => void): Request<FeatureDevProxyClient.Types.StopTransformationResponse, AWSError>;
  /**
   * 
   */
  stopTransformation(callback?: (err: AWSError, data: FeatureDevProxyClient.Types.StopTransformationResponse) => void): Request<FeatureDevProxyClient.Types.StopTransformationResponse, AWSError>;
}
declare namespace FeatureDevProxyClient {
  export type ActiveFunctionalityList = FunctionalityName[];
  export interface AdditionalContentEntry {
    name: AdditionalContentEntryNameString;
    description: AdditionalContentEntryDescriptionString;
    innerContext?: AdditionalContentEntryInnerContextString;
  }
  export type AdditionalContentEntryDescriptionString = string;
  export type AdditionalContentEntryInnerContextString = string;
  export type AdditionalContentEntryNameString = string;
  export type AdditionalContentList = AdditionalContentEntry[];
  export interface AppStudioState {
    namespace: AppStudioStateNamespaceString;
    propertyName: AppStudioStatePropertyNameString;
    propertyValue?: AppStudioStatePropertyValueString;
    propertyContext: AppStudioStatePropertyContextString;
  }
  export type AppStudioStateNamespaceString = string;
  export type AppStudioStatePropertyContextString = string;
  export type AppStudioStatePropertyNameString = string;
  export type AppStudioStatePropertyValueString = string;
  export interface ApplicationProperties {
    tenantId: TenantId;
    applicationArn: ResourceArn;
    tenantUrl: Url;
    applicationType: FunctionalityName;
  }
  export type ApplicationPropertiesList = ApplicationProperties[];
  export type ArtifactId = string;
  export type ArtifactMap = {[key: string]: UploadId};
  export type ArtifactType = "SourceCode"|"BuiltJars"|string;
  export interface AssistantResponseMessage {
    messageId?: MessageId;
    content: AssistantResponseMessageContentString;
    supplementaryWebLinks?: SupplementaryWebLinks;
    references?: References;
    followupPrompt?: FollowupPrompt;
    toolUses?: ToolUses;
  }
  export type AssistantResponseMessageContentString = string;
  export type AttributesMap = {[key: string]: StringList};
  export type AttributesMapKeyString = string;
  export type Base64EncodedPaginationToken = string;
  export type Boolean = boolean;
  export interface ByUserAnalytics {
    s3Uri?: S3Uri;
    toggle: OptInFeatureToggle;
  }
  export interface ChatAddMessageEvent {
    conversationId: ConversationId;
    messageId: MessageId;
    customizationArn?: CustomizationArn;
    userIntent?: UserIntent;
    hasCodeSnippet?: Boolean;
    programmingLanguage?: ProgrammingLanguage;
    activeEditorTotalCharacters?: Integer;
    timeToFirstChunkMilliseconds?: Double;
    timeBetweenChunks?: timeBetweenChunks;
    fullResponselatency?: Double;
    requestLength?: Integer;
    responseLength?: Integer;
    numberOfCodeBlocks?: Integer;
    hasProjectLevelContext?: Boolean;
  }
  export type ChatHistory = ChatMessage[];
  export interface ChatInteractWithMessageEvent {
    conversationId: ConversationId;
    messageId: MessageId;
    customizationArn?: CustomizationArn;
    interactionType?: ChatMessageInteractionType;
    interactionTarget?: ChatInteractWithMessageEventInteractionTargetString;
    acceptedCharacterCount?: Integer;
    acceptedLineCount?: Integer;
    acceptedSnippetHasReference?: Boolean;
    hasProjectLevelContext?: Boolean;
    userIntent?: UserIntent;
    addedIdeDiagnostics?: IdeDiagnosticList;
    removedIdeDiagnostics?: IdeDiagnosticList;
  }
  export type ChatInteractWithMessageEventInteractionTargetString = string;
  export interface ChatMessage {
    userInputMessage?: UserInputMessage;
    assistantResponseMessage?: AssistantResponseMessage;
  }
  export type ChatMessageInteractionType = "INSERT_AT_CURSOR"|"COPY_SNIPPET"|"COPY"|"CLICK_LINK"|"CLICK_BODY_LINK"|"CLICK_FOLLOW_UP"|"HOVER_REFERENCE"|"UPVOTE"|"DOWNVOTE"|string;
  export type ChatTriggerType = "MANUAL"|"DIAGNOSTIC"|"INLINE_CHAT"|string;
  export interface ChatUserModificationEvent {
    conversationId: ConversationId;
    customizationArn?: CustomizationArn;
    messageId: MessageId;
    programmingLanguage?: ProgrammingLanguage;
    modificationPercentage: Double;
    hasProjectLevelContext?: Boolean;
  }
  export type ClientId = string;
  export type CodeAnalysisFindingsSchema = "codeanalysis/findings/1.0"|string;
  export type CodeAnalysisScope = "FILE"|"PROJECT"|string;
  export type CodeAnalysisStatus = "Completed"|"Pending"|"Failed"|string;
  export interface CodeAnalysisUploadContext {
    codeScanName: CodeScanName;
  }
  export interface CodeCoverageEvent {
    customizationArn?: CustomizationArn;
    programmingLanguage: ProgrammingLanguage;
    acceptedCharacterCount: PrimitiveInteger;
    totalCharacterCount: PrimitiveInteger;
    timestamp: Timestamp;
    unmodifiedAcceptedCharacterCount?: PrimitiveInteger;
    totalNewCodeCharacterCount?: PrimitiveInteger;
    totalNewCodeLineCount?: PrimitiveInteger;
    userWrittenCodeCharacterCount?: CodeCoverageEventUserWrittenCodeCharacterCountInteger;
    userWrittenCodeLineCount?: CodeCoverageEventUserWrittenCodeLineCountInteger;
  }
  export type CodeCoverageEventUserWrittenCodeCharacterCountInteger = number;
  export type CodeCoverageEventUserWrittenCodeLineCountInteger = number;
  export interface CodeDescription {
    href: CodeDescriptionHrefString;
  }
  export type CodeDescriptionHrefString = string;
  export interface CodeFixAcceptanceEvent {
    jobId: String;
    ruleId?: String;
    detectorId?: String;
    findingId?: String;
    programmingLanguage?: ProgrammingLanguage;
    linesOfCodeAccepted?: Integer;
    charsOfCodeAccepted?: Integer;
  }
  export interface CodeFixGenerationEvent {
    jobId: String;
    ruleId?: String;
    detectorId?: String;
    findingId?: String;
    programmingLanguage?: ProgrammingLanguage;
    linesOfCodeGenerated?: Integer;
    charsOfCodeGenerated?: Integer;
  }
  export type CodeFixJobStatus = "Succeeded"|"InProgress"|"Failed"|string;
  export type CodeFixName = string;
  export interface CodeFixUploadContext {
    codeFixName: CodeFixName;
  }
  export type CodeGenerationId = string;
  export interface CodeGenerationStatus {
    status: CodeGenerationWorkflowStatus;
    currentStage: CodeGenerationWorkflowStage;
  }
  export type CodeGenerationStatusDetail = string;
  export type CodeGenerationWorkflowStage = "InitialCodeGeneration"|"CodeRefinement"|string;
  export type CodeGenerationWorkflowStatus = "InProgress"|"Complete"|"Failed"|string;
  export interface CodeScanEvent {
    programmingLanguage: ProgrammingLanguage;
    codeScanJobId: CodeScanJobId;
    timestamp: Timestamp;
    codeAnalysisScope?: CodeAnalysisScope;
  }
  export interface CodeScanFailedEvent {
    programmingLanguage: ProgrammingLanguage;
    codeScanJobId: CodeScanJobId;
    timestamp: Timestamp;
    codeAnalysisScope?: CodeAnalysisScope;
  }
  export type CodeScanJobId = string;
  export type CodeScanName = string;
  export interface CodeScanRemediationsEvent {
    programmingLanguage?: ProgrammingLanguage;
    CodeScanRemediationsEventType?: CodeScanRemediationsEventType;
    timestamp?: Timestamp;
    detectorId?: String;
    findingId?: String;
    ruleId?: String;
    component?: String;
    reason?: String;
    result?: String;
    includesFix?: Boolean;
  }
  export type CodeScanRemediationsEventType = "CODESCAN_ISSUE_HOVER"|"CODESCAN_ISSUE_APPLY_FIX"|"CODESCAN_ISSUE_VIEW_DETAILS"|string;
  export interface CodeScanSucceededEvent {
    programmingLanguage: ProgrammingLanguage;
    codeScanJobId: CodeScanJobId;
    timestamp: Timestamp;
    numberOfFindings: PrimitiveInteger;
    codeAnalysisScope?: CodeAnalysisScope;
  }
  export interface Completion {
    content: CompletionContentString;
    references?: References;
    mostRelevantMissingImports?: Imports;
  }
  export type CompletionContentString = string;
  export type CompletionType = "BLOCK"|"LINE"|string;
  export type Completions = Completion[];
  export interface ConsoleState {
    region?: String;
    consoleUrl?: SensitiveString;
    serviceId?: String;
    serviceConsolePage?: String;
    serviceSubconsolePage?: String;
    taskName?: SensitiveString;
  }
  export type ContentChecksumType = "SHA_256"|string;
  export type ContextTruncationScheme = "ANALYSIS"|"GUMBY"|string;
  export type ConversationId = string;
  export interface ConversationState {
    conversationId?: ConversationId;
    history?: ChatHistory;
    currentMessage: ChatMessage;
    chatTriggerType: ChatTriggerType;
    customizationArn?: ResourceArn;
  }
  export interface CreateTaskAssistConversationRequest {
    profileArn?: ProfileArn;
  }
  export interface CreateTaskAssistConversationResponse {
    conversationId: ConversationId;
  }
  export interface CreateUploadUrlRequest {
    contentMd5?: CreateUploadUrlRequestContentMd5String;
    contentChecksum?: CreateUploadUrlRequestContentChecksumString;
    contentChecksumType?: ContentChecksumType;
    contentLength?: CreateUploadUrlRequestContentLengthLong;
    artifactType?: ArtifactType;
    uploadIntent?: UploadIntent;
    uploadContext?: UploadContext;
    uploadId?: UploadId;
    profileArn?: ProfileArn;
  }
  export type CreateUploadUrlRequestContentChecksumString = string;
  export type CreateUploadUrlRequestContentLengthLong = number;
  export type CreateUploadUrlRequestContentMd5String = string;
  export interface CreateUploadUrlResponse {
    uploadId: UploadId;
    uploadUrl: PreSignedUrl;
    kmsKeyArn?: ResourceArn;
    requestHeaders?: RequestHeaders;
  }
  export interface CreateUserMemoryEntryInput {
    memoryEntryString: CreateUserMemoryEntryInputMemoryEntryStringString;
    origin: Origin;
    profileArn?: CreateUserMemoryEntryInputProfileArnString;
    clientToken?: String;
  }
  export type CreateUserMemoryEntryInputMemoryEntryStringString = string;
  export type CreateUserMemoryEntryInputProfileArnString = string;
  export interface CreateUserMemoryEntryOutput {
    memoryEntry: MemoryEntry;
  }
  export interface CreateWorkspaceRequest {
    workspaceRoot: CreateWorkspaceRequestWorkspaceRootString;
    profileArn?: ProfileArn;
  }
  export type CreateWorkspaceRequestWorkspaceRootString = string;
  export interface CreateWorkspaceResponse {
    workspace: WorkspaceMetadata;
  }
  export interface CursorState {
    position?: Position;
    range?: Range;
  }
  export interface Customization {
    arn: CustomizationArn;
    name?: CustomizationName;
    description?: Description;
  }
  export type CustomizationArn = string;
  export type CustomizationName = string;
  export type Customizations = Customization[];
  export interface DashboardAnalytics {
    toggle: OptInFeatureToggle;
  }
  export interface DeleteTaskAssistConversationRequest {
    conversationId: ConversationId;
    profileArn?: ProfileArn;
  }
  export interface DeleteTaskAssistConversationResponse {
    conversationId: ConversationId;
  }
  export interface DeleteUserMemoryEntryInput {
    id: DeleteUserMemoryEntryInputIdString;
    profileArn?: DeleteUserMemoryEntryInputProfileArnString;
  }
  export type DeleteUserMemoryEntryInputIdString = string;
  export type DeleteUserMemoryEntryInputProfileArnString = string;
  export interface DeleteUserMemoryEntryOutput {
  }
  export interface DeleteWorkspaceRequest {
    workspaceId: UUID;
    profileArn?: ProfileArn;
  }
  export interface DeleteWorkspaceResponse {
  }
  export type Description = string;
  export interface Diagnostic {
    textDocumentDiagnostic?: TextDocumentDiagnostic;
    runtimeDiagnostic?: RuntimeDiagnostic;
  }
  export interface DiagnosticLocation {
    uri: DiagnosticLocationUriString;
    range: Range;
  }
  export type DiagnosticLocationUriString = string;
  export interface DiagnosticRelatedInformation {
    location: DiagnosticLocation;
    message: DiagnosticRelatedInformationMessageString;
  }
  export type DiagnosticRelatedInformationList = DiagnosticRelatedInformation[];
  export type DiagnosticRelatedInformationMessageString = string;
  export type DiagnosticSeverity = "ERROR"|"WARNING"|"INFORMATION"|"HINT"|string;
  export type DiagnosticTag = "UNNECESSARY"|"DEPRECATED"|string;
  export type DiagnosticTagList = DiagnosticTag[];
  export interface Dimension {
    name?: DimensionNameString;
    value?: DimensionValueString;
  }
  export type DimensionList = Dimension[];
  export type DimensionNameString = string;
  export type DimensionValueString = string;
  export type DocFolderLevel = "SUB_FOLDER"|"ENTIRE_WORKSPACE"|string;
  export interface DocGenerationEvent {
    conversationId: ConversationId;
    numberOfAddChars?: PrimitiveInteger;
    numberOfAddLines?: PrimitiveInteger;
    numberOfAddFiles?: PrimitiveInteger;
    userDecision?: DocUserDecision;
    interactionType?: DocInteractionType;
    userIdentity?: String;
    numberOfNavigation?: PrimitiveInteger;
    folderLevel?: DocFolderLevel;
  }
  export type DocInteractionType = "GENERATE_README"|"UPDATE_README"|"EDIT_README"|string;
  export type DocUserDecision = "ACCEPT"|"REJECT"|string;
  export interface DocV2AcceptanceEvent {
    conversationId: ConversationId;
    numberOfAddedChars: DocV2AcceptanceEventNumberOfAddedCharsInteger;
    numberOfAddedLines: DocV2AcceptanceEventNumberOfAddedLinesInteger;
    numberOfAddedFiles: DocV2AcceptanceEventNumberOfAddedFilesInteger;
    userDecision: DocUserDecision;
    interactionType: DocInteractionType;
    numberOfNavigations: DocV2AcceptanceEventNumberOfNavigationsInteger;
    folderLevel: DocFolderLevel;
  }
  export type DocV2AcceptanceEventNumberOfAddedCharsInteger = number;
  export type DocV2AcceptanceEventNumberOfAddedFilesInteger = number;
  export type DocV2AcceptanceEventNumberOfAddedLinesInteger = number;
  export type DocV2AcceptanceEventNumberOfNavigationsInteger = number;
  export interface DocV2GenerationEvent {
    conversationId: ConversationId;
    numberOfGeneratedChars: DocV2GenerationEventNumberOfGeneratedCharsInteger;
    numberOfGeneratedLines: DocV2GenerationEventNumberOfGeneratedLinesInteger;
    numberOfGeneratedFiles: DocV2GenerationEventNumberOfGeneratedFilesInteger;
    interactionType?: DocInteractionType;
    numberOfNavigations?: DocV2GenerationEventNumberOfNavigationsInteger;
    folderLevel?: DocFolderLevel;
  }
  export type DocV2GenerationEventNumberOfGeneratedCharsInteger = number;
  export type DocV2GenerationEventNumberOfGeneratedFilesInteger = number;
  export type DocV2GenerationEventNumberOfGeneratedLinesInteger = number;
  export type DocV2GenerationEventNumberOfNavigationsInteger = number;
  export interface DocumentSymbol {
    name: DocumentSymbolNameString;
    type: SymbolType;
    source?: DocumentSymbolSourceString;
  }
  export type DocumentSymbolNameString = string;
  export type DocumentSymbolSourceString = string;
  export type DocumentSymbols = DocumentSymbol[];
  export interface DocumentationIntentContext {
    scope?: DocumentationIntentContextScopeString;
    type: DocumentationType;
  }
  export type DocumentationIntentContextScopeString = string;
  export type DocumentationType = "README"|string;
  export type Double = number;
  export interface EditorState {
    document?: TextDocument;
    cursorState?: CursorState;
    relevantDocuments?: RelevantDocumentList;
    useRelevantDocuments?: Boolean;
    workspaceFolders?: WorkspaceFolderList;
  }
  export interface EnvState {
    operatingSystem?: EnvStateOperatingSystemString;
    currentWorkingDirectory?: EnvStateCurrentWorkingDirectoryString;
    environmentVariables?: EnvironmentVariables;
    timezoneOffset?: EnvStateTimezoneOffsetInteger;
  }
  export type EnvStateCurrentWorkingDirectoryString = string;
  export type EnvStateOperatingSystemString = string;
  export type EnvStateTimezoneOffsetInteger = number;
  export interface EnvironmentVariable {
    key?: EnvironmentVariableKeyString;
    value?: EnvironmentVariableValueString;
  }
  export type EnvironmentVariableKeyString = string;
  export type EnvironmentVariableValueString = string;
  export type EnvironmentVariables = EnvironmentVariable[];
  export type ErrorDetails = string;
  export interface Event {
    eventId: UUID;
    generationId: UUID;
    eventTimestamp: SyntheticTimestamp_date_time;
    eventType: EventType;
    eventBlob: EventBlob;
  }
  export type EventBlob = Buffer|Uint8Array|Blob|string;
  export type EventList = Event[];
  export type EventType = string;
  export interface ExternalIdentityDetails {
    issuerUrl?: IssuerUrl;
    clientId?: ClientId;
    scimEndpoint?: String;
  }
  export interface FeatureDevCodeAcceptanceEvent {
    conversationId: ConversationId;
    linesOfCodeAccepted: FeatureDevCodeAcceptanceEventLinesOfCodeAcceptedInteger;
    charactersOfCodeAccepted: FeatureDevCodeAcceptanceEventCharactersOfCodeAcceptedInteger;
    programmingLanguage?: ProgrammingLanguage;
  }
  export type FeatureDevCodeAcceptanceEventCharactersOfCodeAcceptedInteger = number;
  export type FeatureDevCodeAcceptanceEventLinesOfCodeAcceptedInteger = number;
  export interface FeatureDevCodeGenerationEvent {
    conversationId: ConversationId;
    linesOfCodeGenerated: FeatureDevCodeGenerationEventLinesOfCodeGeneratedInteger;
    charactersOfCodeGenerated: FeatureDevCodeGenerationEventCharactersOfCodeGeneratedInteger;
    programmingLanguage?: ProgrammingLanguage;
  }
  export type FeatureDevCodeGenerationEventCharactersOfCodeGeneratedInteger = number;
  export type FeatureDevCodeGenerationEventLinesOfCodeGeneratedInteger = number;
  export interface FeatureDevEvent {
    conversationId: ConversationId;
  }
  export interface FeatureEvaluation {
    feature: FeatureName;
    variation: FeatureVariation;
    value: FeatureValue;
  }
  export type FeatureEvaluationsList = FeatureEvaluation[];
  export type FeatureName = string;
  export interface FeatureValue {
    boolValue?: Boolean;
    doubleValue?: Double;
    longValue?: Long;
    stringValue?: FeatureValueStringType;
  }
  export type FeatureValueStringType = string;
  export type FeatureVariation = string;
  export interface FileContext {
    leftFileContent: FileContextLeftFileContentString;
    rightFileContent: FileContextRightFileContentString;
    filename: FileContextFilenameString;
    programmingLanguage: ProgrammingLanguage;
  }
  export type FileContextFilenameString = string;
  export type FileContextLeftFileContentString = string;
  export type FileContextRightFileContentString = string;
  export interface FollowupPrompt {
    content: FollowupPromptContentString;
    userIntent?: UserIntent;
  }
  export type FollowupPromptContentString = string;
  export type FunctionalityName = "COMPLETIONS"|"ANALYSIS"|"CONVERSATIONS"|"TASK_ASSIST"|"TRANSFORMATIONS"|"CHAT_CUSTOMIZATION"|"TRANSFORMATIONS_WEBAPP"|"FEATURE_DEVELOPMENT"|string;
  export interface GenerateCompletionsRequest {
    fileContext: FileContext;
    maxResults?: GenerateCompletionsRequestMaxResultsInteger;
    nextToken?: GenerateCompletionsRequestNextTokenString;
    referenceTrackerConfiguration?: ReferenceTrackerConfiguration;
    supplementalContexts?: SupplementalContextList;
    customizationArn?: CustomizationArn;
    optOutPreference?: OptOutPreference;
    userContext?: UserContext;
    profileArn?: ProfileArn;
    workspaceId?: UUID;
  }
  export type GenerateCompletionsRequestMaxResultsInteger = number;
  export type GenerateCompletionsRequestNextTokenString = string;
  export interface GenerateCompletionsResponse {
    completions?: Completions;
    nextToken?: SensitiveString;
  }
  export interface GetCodeAnalysisRequest {
    jobId: GetCodeAnalysisRequestJobIdString;
    profileArn?: ProfileArn;
  }
  export type GetCodeAnalysisRequestJobIdString = string;
  export interface GetCodeAnalysisResponse {
    status: CodeAnalysisStatus;
    errorMessage?: SensitiveString;
  }
  export interface GetCodeFixJobRequest {
    jobId: GetCodeFixJobRequestJobIdString;
    profileArn?: ProfileArn;
  }
  export type GetCodeFixJobRequestJobIdString = string;
  export interface GetCodeFixJobResponse {
    jobStatus?: CodeFixJobStatus;
    suggestedFix?: SuggestedFix;
  }
  export interface GetTaskAssistCodeGenerationRequest {
    conversationId: ConversationId;
    codeGenerationId: CodeGenerationId;
    profileArn?: ProfileArn;
  }
  export interface GetTaskAssistCodeGenerationResponse {
    conversationId: ConversationId;
    codeGenerationStatus: CodeGenerationStatus;
    codeGenerationStatusDetail?: CodeGenerationStatusDetail;
    codeGenerationRemainingIterationCount?: Integer;
    codeGenerationTotalIterationCount?: Integer;
  }
  export interface GetTestGenerationRequest {
    testGenerationJobGroupName: TestGenerationJobGroupName;
    testGenerationJobId: UUID;
    profileArn?: ProfileArn;
  }
  export interface GetTestGenerationResponse {
    testGenerationJob?: TestGenerationJob;
  }
  export interface GetTransformationPlanRequest {
    transformationJobId: TransformationJobId;
    profileArn?: ProfileArn;
  }
  export interface GetTransformationPlanResponse {
    transformationPlan: TransformationPlan;
  }
  export interface GetTransformationRequest {
    transformationJobId: TransformationJobId;
    profileArn?: ProfileArn;
  }
  export interface GetTransformationResponse {
    transformationJob: TransformationJob;
  }
  export interface GitState {
    status?: GitStateStatusString;
  }
  export type GitStateStatusString = string;
  export type IdeCategory = "JETBRAINS"|"VSCODE"|"CLI"|"JUPYTER_MD"|"JUPYTER_SM"|"ECLIPSE"|"VISUAL_STUDIO"|string;
  export interface IdeDiagnostic {
    range?: Range;
    source?: IdeDiagnosticSourceString;
    severity?: DiagnosticSeverity;
    ideDiagnosticType: IdeDiagnosticType;
  }
  export type IdeDiagnosticList = IdeDiagnostic[];
  export type IdeDiagnosticSourceString = string;
  export type IdeDiagnosticType = "SYNTAX_ERROR"|"TYPE_ERROR"|"REFERENCE_ERROR"|"BEST_PRACTICE"|"SECURITY"|"OTHER"|string;
  export type IdempotencyToken = string;
  export interface IdentityDetails {
    ssoIdentityDetails?: SSOIdentityDetails;
    externalIdentityDetails?: ExternalIdentityDetails;
  }
  export interface ImageBlock {
    format: ImageFormat;
    source: ImageSource;
  }
  export type ImageBlocks = ImageBlock[];
  export type ImageFormat = "png"|"jpeg"|"gif"|"webp"|string;
  export interface ImageSource {
    bytes?: ImageSourceBytesBlob;
  }
  export type ImageSourceBytesBlob = Buffer|Uint8Array|Blob|string;
  export interface Import {
    statement?: ImportStatementString;
  }
  export type ImportStatementString = string;
  export type Imports = Import[];
  export interface InlineChatEvent {
    requestId: UUID;
    timestamp: Timestamp;
    inputLength?: PrimitiveInteger;
    numSelectedLines?: PrimitiveInteger;
    numSuggestionAddChars?: PrimitiveInteger;
    numSuggestionAddLines?: PrimitiveInteger;
    numSuggestionDelChars?: PrimitiveInteger;
    numSuggestionDelLines?: PrimitiveInteger;
    codeIntent?: Boolean;
    userDecision?: InlineChatUserDecision;
    responseStartLatency?: Double;
    responseEndLatency?: Double;
    programmingLanguage?: ProgrammingLanguage;
  }
  export type InlineChatUserDecision = "ACCEPT"|"REJECT"|"DISMISS"|string;
  export type Integer = number;
  export type Intent = "DEV"|"DOC"|string;
  export interface IntentContext {
    documentation?: DocumentationIntentContext;
  }
  export type IssuerUrl = string;
  export type LineRangeList = Range[];
  export interface ListAvailableCustomizationsRequest {
    maxResults?: ListAvailableCustomizationsRequestMaxResultsInteger;
    nextToken?: Base64EncodedPaginationToken;
    profileArn?: ProfileArn;
  }
  export type ListAvailableCustomizationsRequestMaxResultsInteger = number;
  export interface ListAvailableCustomizationsResponse {
    customizations: Customizations;
    nextToken?: Base64EncodedPaginationToken;
  }
  export interface ListAvailableProfilesRequest {
    maxResults?: ListAvailableProfilesRequestMaxResultsInteger;
    nextToken?: Base64EncodedPaginationToken;
  }
  export type ListAvailableProfilesRequestMaxResultsInteger = number;
  export interface ListAvailableProfilesResponse {
    profiles: ProfileList;
    nextToken?: Base64EncodedPaginationToken;
  }
  export interface ListCodeAnalysisFindingsRequest {
    jobId: ListCodeAnalysisFindingsRequestJobIdString;
    nextToken?: PaginationToken;
    codeAnalysisFindingsSchema: CodeAnalysisFindingsSchema;
    profileArn?: ProfileArn;
  }
  export type ListCodeAnalysisFindingsRequestJobIdString = string;
  export interface ListCodeAnalysisFindingsResponse {
    nextToken?: PaginationToken;
    codeAnalysisFindings: SensitiveString;
  }
  export interface ListEventsRequest {
    conversationId: UUID;
    maxResults?: ListEventsRequestMaxResultsInteger;
    nextToken?: NextToken;
  }
  export type ListEventsRequestMaxResultsInteger = number;
  export interface ListEventsResponse {
    conversationId: UUID;
    events: EventList;
    nextToken?: NextToken;
  }
  export interface ListFeatureEvaluationsRequest {
    userContext: UserContext;
    profileArn?: ProfileArn;
  }
  export interface ListFeatureEvaluationsResponse {
    featureEvaluations: FeatureEvaluationsList;
  }
  export interface ListUserMemoryEntriesInput {
    maxResults?: ListUserMemoryEntriesInputMaxResultsInteger;
    profileArn?: ListUserMemoryEntriesInputProfileArnString;
    nextToken?: ListUserMemoryEntriesInputNextTokenString;
  }
  export type ListUserMemoryEntriesInputMaxResultsInteger = number;
  export type ListUserMemoryEntriesInputNextTokenString = string;
  export type ListUserMemoryEntriesInputProfileArnString = string;
  export interface ListUserMemoryEntriesOutput {
    memoryEntries: MemoryEntryList;
    nextToken?: ListUserMemoryEntriesOutputNextTokenString;
  }
  export type ListUserMemoryEntriesOutputNextTokenString = string;
  export interface ListWorkspaceMetadataRequest {
    workspaceRoot?: ListWorkspaceMetadataRequestWorkspaceRootString;
    nextToken?: String;
    maxResults?: Integer;
    profileArn?: ProfileArn;
  }
  export type ListWorkspaceMetadataRequestWorkspaceRootString = string;
  export interface ListWorkspaceMetadataResponse {
    workspaces: WorkspaceList;
    nextToken?: String;
  }
  export type Long = number;
  export interface MemoryEntry {
    id: MemoryEntryIdString;
    memoryEntryString: MemoryEntryMemoryEntryStringString;
    metadata: MemoryEntryMetadata;
  }
  export type MemoryEntryIdString = string;
  export type MemoryEntryList = MemoryEntry[];
  export type MemoryEntryMemoryEntryStringString = string;
  export interface MemoryEntryMetadata {
    origin: Origin;
    attributes?: AttributesMap;
    createdAt: Timestamp;
    updatedAt: Timestamp;
  }
  export type MessageId = string;
  export interface MetricData {
    metricName: MetricDataMetricNameString;
    metricValue: Double;
    timestamp: Timestamp;
    product: MetricDataProductString;
    dimensions?: DimensionList;
  }
  export type MetricDataMetricNameString = string;
  export type MetricDataProductString = string;
  export type NextToken = string;
  export type Notifications = NotificationsFeature[];
  export interface NotificationsFeature {
    feature: FeatureName;
    toggle: OptInFeatureToggle;
  }
  export type OperatingSystem = "MAC"|"WINDOWS"|"LINUX"|string;
  export type OptInFeatureToggle = "ON"|"OFF"|string;
  export interface OptInFeatures {
    promptLogging?: PromptLogging;
    byUserAnalytics?: ByUserAnalytics;
    dashboardAnalytics?: DashboardAnalytics;
    notifications?: Notifications;
    workspaceContext?: WorkspaceContext;
  }
  export type OptOutPreference = "OPTIN"|"OPTOUT"|string;
  export type Origin = "CHATBOT"|"CONSOLE"|"DOCUMENTATION"|"MARKETING"|"MOBILE"|"SERVICE_INTERNAL"|"UNIFIED_SEARCH"|"UNKNOWN"|"MD"|"IDE"|"SAGE_MAKER"|"CLI"|"AI_EDITOR"|"OPENSEARCH_DASHBOARD"|"GITLAB"|string;
  export interface PackageInfo {
    executionCommand?: SensitiveString;
    buildCommand?: SensitiveString;
    buildOrder?: PackageInfoBuildOrderInteger;
    testFramework?: String;
    packageSummary?: PackageInfoPackageSummaryString;
    packagePlan?: PackageInfoPackagePlanString;
    targetFileInfoList?: TargetFileInfoList;
  }
  export type PackageInfoBuildOrderInteger = number;
  export type PackageInfoList = PackageInfo[];
  export type PackageInfoPackagePlanString = string;
  export type PackageInfoPackageSummaryString = string;
  export type PaginationToken = string;
  export interface Position {
    line: Integer;
    character: Integer;
  }
  export type PreSignedUrl = string;
  export type PrimitiveInteger = number;
  export interface Profile {
    arn: ProfileArn;
    identityDetails?: IdentityDetails;
    profileName: ProfileName;
    description?: ProfileDescription;
    referenceTrackerConfiguration?: ReferenceTrackerConfiguration;
    kmsKeyArn?: ResourceArn;
    activeFunctionalities?: ActiveFunctionalityList;
    status?: ProfileStatus;
    errorDetails?: ErrorDetails;
    resourcePolicy?: ResourcePolicy;
    profileType?: ProfileType;
    optInFeatures?: OptInFeatures;
    permissionUpdateRequired?: Boolean;
    applicationProperties?: ApplicationPropertiesList;
  }
  export type ProfileArn = string;
  export type ProfileDescription = string;
  export type ProfileList = Profile[];
  export type ProfileName = string;
  export type ProfileStatus = "ACTIVE"|"CREATING"|"CREATE_FAILED"|"UPDATING"|"UPDATE_FAILED"|"DELETING"|"DELETE_FAILED"|string;
  export type ProfileType = "Q_DEVELOPER"|"CODEWHISPERER"|string;
  export interface ProgrammingLanguage {
    languageName: ProgrammingLanguageLanguageNameString;
  }
  export type ProgrammingLanguageLanguageNameString = string;
  export type ProgressUpdates = TransformationProgressUpdate[];
  export interface PromptLogging {
    s3Uri: S3Uri;
    toggle: OptInFeatureToggle;
  }
  export interface Range {
    start: Position;
    end: Position;
  }
  export type RecommendationsWithReferencesPreference = "BLOCK"|"ALLOW"|string;
  export interface Reference {
    licenseName?: ReferenceLicenseNameString;
    repository?: ReferenceRepositoryString;
    url?: ReferenceUrlString;
    recommendationContentSpan?: Span;
  }
  export type ReferenceLicenseNameString = string;
  export type ReferenceRepositoryString = string;
  export interface ReferenceTrackerConfiguration {
    recommendationsWithReferences: RecommendationsWithReferencesPreference;
  }
  export type ReferenceUrlString = string;
  export type References = Reference[];
  export type RelevantDocumentList = RelevantTextDocument[];
  export interface RelevantTextDocument {
    relativeFilePath: RelevantTextDocumentRelativeFilePathString;
    programmingLanguage?: ProgrammingLanguage;
    text?: RelevantTextDocumentTextString;
    documentSymbols?: DocumentSymbols;
  }
  export type RelevantTextDocumentRelativeFilePathString = string;
  export type RelevantTextDocumentTextString = string;
  export type RequestHeaderKey = string;
  export type RequestHeaderValue = string;
  export type RequestHeaders = {[key: string]: RequestHeaderValue};
  export type ResourceArn = string;
  export interface ResourcePolicy {
    effect: ResourcePolicyEffect;
  }
  export type ResourcePolicyEffect = "ALLOW"|"DENY"|string;
  export interface ResumeTransformationRequest {
    transformationJobId: TransformationJobId;
    userActionStatus?: TransformationUserActionStatus;
    profileArn?: ProfileArn;
  }
  export interface ResumeTransformationResponse {
    transformationStatus: TransformationStatus;
  }
  export interface RuntimeDiagnostic {
    source: RuntimeDiagnosticSourceString;
    severity: DiagnosticSeverity;
    message: RuntimeDiagnosticMessageString;
  }
  export type RuntimeDiagnosticMessageString = string;
  export type RuntimeDiagnosticSourceString = string;
  export type S3Uri = string;
  export interface SSOIdentityDetails {
    instanceArn: ResourceArn;
    oidcClientId: String;
    ssoRegion?: SSORegion;
  }
  export type SSORegion = string;
  export interface SendTelemetryEventRequest {
    clientToken?: IdempotencyToken;
    telemetryEvent: TelemetryEvent;
    optOutPreference?: OptOutPreference;
    userContext?: UserContext;
    profileArn?: ProfileArn;
  }
  export interface SendTelemetryEventResponse {
  }
  export interface SensitiveDocument {
  }
  export type SensitiveString = string;
  export type ShellHistory = ShellHistoryEntry[];
  export interface ShellHistoryEntry {
    command: ShellHistoryEntryCommandString;
    directory?: ShellHistoryEntryDirectoryString;
    exitCode?: Integer;
    stdout?: ShellHistoryEntryStdoutString;
    stderr?: ShellHistoryEntryStderrString;
  }
  export type ShellHistoryEntryCommandString = string;
  export type ShellHistoryEntryDirectoryString = string;
  export type ShellHistoryEntryStderrString = string;
  export type ShellHistoryEntryStdoutString = string;
  export interface ShellState {
    shellName: ShellStateShellNameString;
    shellHistory?: ShellHistory;
  }
  export type ShellStateShellNameString = string;
  export interface Span {
    start?: SpanStartInteger;
    end?: SpanEndInteger;
  }
  export type SpanEndInteger = number;
  export type SpanStartInteger = number;
  export interface StartCodeAnalysisRequest {
    artifacts: ArtifactMap;
    programmingLanguage: ProgrammingLanguage;
    clientToken?: StartCodeAnalysisRequestClientTokenString;
    scope?: CodeAnalysisScope;
    codeScanName?: CodeScanName;
    profileArn?: ProfileArn;
  }
  export type StartCodeAnalysisRequestClientTokenString = string;
  export interface StartCodeAnalysisResponse {
    jobId: StartCodeAnalysisResponseJobIdString;
    status: CodeAnalysisStatus;
    errorMessage?: SensitiveString;
  }
  export type StartCodeAnalysisResponseJobIdString = string;
  export interface StartCodeFixJobRequest {
    snippetRange: Range;
    uploadId: UploadId;
    description?: StartCodeFixJobRequestDescriptionString;
    ruleId?: StartCodeFixJobRequestRuleIdString;
    codeFixName?: CodeFixName;
    referenceTrackerConfiguration?: ReferenceTrackerConfiguration;
    profileArn?: ProfileArn;
  }
  export type StartCodeFixJobRequestDescriptionString = string;
  export type StartCodeFixJobRequestRuleIdString = string;
  export interface StartCodeFixJobResponse {
    jobId?: StartCodeFixJobResponseJobIdString;
    status?: CodeFixJobStatus;
  }
  export type StartCodeFixJobResponseJobIdString = string;
  export interface StartTaskAssistCodeGenerationRequest {
    conversationState: ConversationState;
    workspaceState: WorkspaceState;
    taskAssistPlan?: TaskAssistPlan;
    codeGenerationId?: CodeGenerationId;
    currentCodeGenerationId?: CodeGenerationId;
    intent?: Intent;
    intentContext?: IntentContext;
    profileArn?: ProfileArn;
  }
  export interface StartTaskAssistCodeGenerationResponse {
    conversationId: ConversationId;
    codeGenerationId: CodeGenerationId;
  }
  export interface StartTestGenerationRequest {
    uploadId: UploadId;
    targetCodeList: TargetCodeList;
    userInput: StartTestGenerationRequestUserInputString;
    testGenerationJobGroupName?: TestGenerationJobGroupName;
    clientToken?: StartTestGenerationRequestClientTokenString;
    profileArn?: ProfileArn;
    referenceTrackerConfiguration?: ReferenceTrackerConfiguration;
  }
  export type StartTestGenerationRequestClientTokenString = string;
  export type StartTestGenerationRequestUserInputString = string;
  export interface StartTestGenerationResponse {
    testGenerationJob?: TestGenerationJob;
  }
  export interface StartTransformationRequest {
    workspaceState: WorkspaceState;
    transformationSpec: TransformationSpec;
    profileArn?: ProfileArn;
  }
  export interface StartTransformationResponse {
    transformationJobId: TransformationJobId;
  }
  export type StepId = string;
  export interface StopTransformationRequest {
    transformationJobId: TransformationJobId;
    profileArn?: ProfileArn;
  }
  export interface StopTransformationResponse {
    transformationStatus: TransformationStatus;
  }
  export type String = string;
  export type StringList = StringListMemberString[];
  export type StringListMemberString = string;
  export interface SuggestedFix {
    codeDiff?: SuggestedFixCodeDiffString;
    description?: SuggestedFixDescriptionString;
    references?: References;
  }
  export type SuggestedFixCodeDiffString = string;
  export type SuggestedFixDescriptionString = string;
  export type SuggestionState = "ACCEPT"|"REJECT"|"DISCARD"|"EMPTY"|"MERGE"|string;
  export interface SupplementalContext {
    filePath: SupplementalContextFilePathString;
    content: SupplementalContextContentString;
  }
  export type SupplementalContextContentString = string;
  export type SupplementalContextFilePathString = string;
  export type SupplementalContextList = SupplementalContext[];
  export interface SupplementaryWebLink {
    url: SupplementaryWebLinkUrlString;
    title: SupplementaryWebLinkTitleString;
    snippet?: SupplementaryWebLinkSnippetString;
  }
  export type SupplementaryWebLinkSnippetString = string;
  export type SupplementaryWebLinkTitleString = string;
  export type SupplementaryWebLinkUrlString = string;
  export type SupplementaryWebLinks = SupplementaryWebLink[];
  export type SymbolType = "DECLARATION"|"USAGE"|string;
  export type SyntheticTimestamp_date_time = Date;
  export interface TargetCode {
    relativeTargetPath: TargetCodeRelativeTargetPathString;
    targetLineRangeList?: LineRangeList;
  }
  export type TargetCodeList = TargetCode[];
  export type TargetCodeRelativeTargetPathString = string;
  export interface TargetFileInfo {
    filePath?: SensitiveString;
    testFilePath?: SensitiveString;
    testCoverage?: TargetFileInfoTestCoverageInteger;
    fileSummary?: TargetFileInfoFileSummaryString;
    filePlan?: TargetFileInfoFilePlanString;
    codeReferences?: References;
    numberOfTestMethods?: TargetFileInfoNumberOfTestMethodsInteger;
  }
  export type TargetFileInfoFilePlanString = string;
  export type TargetFileInfoFileSummaryString = string;
  export type TargetFileInfoList = TargetFileInfo[];
  export type TargetFileInfoNumberOfTestMethodsInteger = number;
  export type TargetFileInfoTestCoverageInteger = number;
  export type TaskAssistPlan = TaskAssistPlanStep[];
  export interface TaskAssistPlanStep {
    filePath: TaskAssistPlanStepFilePathString;
    description: TaskAssistPlanStepDescriptionString;
    startLine?: TaskAssistPlanStepStartLineInteger;
    endLine?: TaskAssistPlanStepEndLineInteger;
    action?: TaskAssistPlanStepAction;
  }
  export type TaskAssistPlanStepAction = "MODIFY"|"CREATE"|"DELETE"|"UNKNOWN"|string;
  export type TaskAssistPlanStepDescriptionString = string;
  export type TaskAssistPlanStepEndLineInteger = number;
  export type TaskAssistPlanStepFilePathString = string;
  export type TaskAssistPlanStepStartLineInteger = number;
  export interface TaskAssistPlanningUploadContext {
    conversationId: ConversationId;
  }
  export interface TelemetryEvent {
    userTriggerDecisionEvent?: UserTriggerDecisionEvent;
    codeCoverageEvent?: CodeCoverageEvent;
    userModificationEvent?: UserModificationEvent;
    codeScanEvent?: CodeScanEvent;
    codeScanSucceededEvent?: CodeScanSucceededEvent;
    codeScanFailedEvent?: CodeScanFailedEvent;
    codeScanRemediationsEvent?: CodeScanRemediationsEvent;
    codeFixGenerationEvent?: CodeFixGenerationEvent;
    codeFixAcceptanceEvent?: CodeFixAcceptanceEvent;
    metricData?: MetricData;
    chatAddMessageEvent?: ChatAddMessageEvent;
    chatInteractWithMessageEvent?: ChatInteractWithMessageEvent;
    chatUserModificationEvent?: ChatUserModificationEvent;
    terminalUserInteractionEvent?: TerminalUserInteractionEvent;
    featureDevEvent?: FeatureDevEvent;
    featureDevCodeGenerationEvent?: FeatureDevCodeGenerationEvent;
    featureDevCodeAcceptanceEvent?: FeatureDevCodeAcceptanceEvent;
    inlineChatEvent?: InlineChatEvent;
    transformEvent?: TransformEvent;
    docGenerationEvent?: DocGenerationEvent;
    docV2GenerationEvent?: DocV2GenerationEvent;
    docV2AcceptanceEvent?: DocV2AcceptanceEvent;
    testGenerationEvent?: TestGenerationEvent;
  }
  export type TenantId = string;
  export interface TerminalUserInteractionEvent {
    terminalUserInteractionEventType?: TerminalUserInteractionEventType;
    terminal?: String;
    terminalVersion?: String;
    shell?: String;
    shellVersion?: String;
    duration?: Integer;
    timeToSuggestion?: Integer;
    isCompletionAccepted?: Boolean;
    cliToolCommand?: String;
  }
  export type TerminalUserInteractionEventType = "CODEWHISPERER_TERMINAL_TRANSLATION_ACTION"|"CODEWHISPERER_TERMINAL_COMPLETION_INSERTED"|string;
  export interface TestGenerationEvent {
    jobId: UUID;
    groupName: TestGenerationJobGroupName;
    timestamp?: Timestamp;
    ideCategory?: IdeCategory;
    programmingLanguage?: ProgrammingLanguage;
    numberOfUnitTestCasesGenerated?: Integer;
    numberOfUnitTestCasesAccepted?: Integer;
    linesOfCodeGenerated?: Integer;
    linesOfCodeAccepted?: Integer;
    charsOfCodeGenerated?: Integer;
    charsOfCodeAccepted?: Integer;
  }
  export interface TestGenerationJob {
    testGenerationJobId: UUID;
    testGenerationJobGroupName: TestGenerationJobGroupName;
    status: TestGenerationJobStatus;
    shortAnswer?: SensitiveString;
    creationTime: Timestamp;
    progressRate?: TestGenerationJobProgressRateInteger;
    jobStatusReason?: String;
    jobSummary?: TestGenerationJobJobSummaryString;
    jobPlan?: TestGenerationJobJobPlanString;
    packageInfoList?: PackageInfoList;
  }
  export type TestGenerationJobGroupName = string;
  export type TestGenerationJobJobPlanString = string;
  export type TestGenerationJobJobSummaryString = string;
  export type TestGenerationJobProgressRateInteger = number;
  export type TestGenerationJobStatus = "IN_PROGRESS"|"FAILED"|"COMPLETED"|string;
  export interface TextDocument {
    relativeFilePath: TextDocumentRelativeFilePathString;
    programmingLanguage?: ProgrammingLanguage;
    text?: TextDocumentTextString;
    documentSymbols?: DocumentSymbols;
  }
  export interface TextDocumentDiagnostic {
    document: TextDocument;
    range: Range;
    source: SensitiveString;
    severity: DiagnosticSeverity;
    message: TextDocumentDiagnosticMessageString;
    code?: Integer;
    codeDescription?: CodeDescription;
    tags?: DiagnosticTagList;
    relatedInformation?: DiagnosticRelatedInformationList;
    data?: TextDocumentDiagnosticDataString;
  }
  export type TextDocumentDiagnosticDataString = string;
  export type TextDocumentDiagnosticMessageString = string;
  export type TextDocumentRelativeFilePathString = string;
  export type TextDocumentTextString = string;
  export type Timestamp = Date;
  export interface Tool {
    toolSpecification?: ToolSpecification;
  }
  export type ToolDescription = string;
  export interface ToolInputSchema {
    json?: SensitiveDocument;
  }
  export type ToolName = string;
  export interface ToolResult {
    toolUseId: ToolUseId;
    content: ToolResultContent;
    status?: ToolResultStatus;
  }
  export type ToolResultContent = ToolResultContentBlock[];
  export interface ToolResultContentBlock {
    text?: ToolResultContentBlockTextString;
    json?: SensitiveDocument;
  }
  export type ToolResultContentBlockTextString = string;
  export type ToolResultStatus = "success"|"error"|string;
  export type ToolResults = ToolResult[];
  export interface ToolSpecification {
    inputSchema: ToolInputSchema;
    name: ToolName;
    description?: ToolDescription;
  }
  export interface ToolUse {
    toolUseId: ToolUseId;
    name: ToolName;
    input: SensitiveDocument;
  }
  export type ToolUseId = string;
  export type ToolUses = ToolUse[];
  export type Tools = Tool[];
  export interface TransformEvent {
    jobId: TransformationJobId;
    timestamp?: Timestamp;
    ideCategory?: IdeCategory;
    programmingLanguage?: ProgrammingLanguage;
    linesOfCodeChanged?: Integer;
    charsOfCodeChanged?: Integer;
    linesOfCodeSubmitted?: Integer;
  }
  export type TransformationDotNetRuntimeEnv = "NET_5_0"|"NET_6_0"|"NET_7_0"|"NET_8_0"|"NET_9_0"|"NET_STANDARD_2_0"|string;
  export interface TransformationDownloadArtifact {
    downloadArtifactType?: TransformationDownloadArtifactType;
    downloadArtifactId?: ArtifactId;
  }
  export type TransformationDownloadArtifactType = "ClientInstructions"|"Logs"|"GeneratedCode"|string;
  export type TransformationDownloadArtifacts = TransformationDownloadArtifact[];
  export type TransformationJavaRuntimeEnv = "JVM_8"|"JVM_11"|"JVM_17"|"JVM_21"|string;
  export interface TransformationJob {
    jobId?: TransformationJobId;
    transformationSpec?: TransformationSpec;
    status?: TransformationStatus;
    reason?: String;
    creationTime?: Timestamp;
    startExecutionTime?: Timestamp;
    endExecutionTime?: Timestamp;
  }
  export type TransformationJobId = string;
  export type TransformationLanguage = "JAVA_8"|"JAVA_11"|"JAVA_17"|"JAVA_21"|"C_SHARP"|"COBOL"|"PL_I"|"JCL"|string;
  export type TransformationLanguages = TransformationLanguage[];
  export type TransformationMainframeRuntimeEnv = "MAINFRAME"|string;
  export type TransformationOperatingSystemFamily = "WINDOWS"|"LINUX"|string;
  export interface TransformationPlan {
    transformationSteps: TransformationSteps;
  }
  export interface TransformationPlatformConfig {
    operatingSystemFamily?: TransformationOperatingSystemFamily;
  }
  export interface TransformationProgressUpdate {
    name: String;
    status: TransformationProgressUpdateStatus;
    description?: String;
    startTime?: Timestamp;
    endTime?: Timestamp;
    downloadArtifacts?: TransformationDownloadArtifacts;
  }
  export type TransformationProgressUpdateStatus = "IN_PROGRESS"|"COMPLETED"|"FAILED"|"PAUSED"|"AWAITING_CLIENT_ACTION"|"SKIPPED"|string;
  export interface TransformationProjectArtifactDescriptor {
    sourceCodeArtifact?: TransformationSourceCodeArtifactDescriptor;
  }
  export interface TransformationProjectState {
    language?: TransformationLanguage;
    runtimeEnv?: TransformationRuntimeEnv;
    platformConfig?: TransformationPlatformConfig;
    projectArtifact?: TransformationProjectArtifactDescriptor;
  }
  export interface TransformationRuntimeEnv {
    java?: TransformationJavaRuntimeEnv;
    dotNet?: TransformationDotNetRuntimeEnv;
    mainframe?: TransformationMainframeRuntimeEnv;
  }
  export interface TransformationSourceCodeArtifactDescriptor {
    languages?: TransformationLanguages;
    runtimeEnv?: TransformationRuntimeEnv;
  }
  export interface TransformationSpec {
    transformationType?: TransformationType;
    source?: TransformationProjectState;
    target?: TransformationProjectState;
  }
  export type TransformationStatus = "CREATED"|"ACCEPTED"|"REJECTED"|"STARTED"|"PREPARING"|"PREPARED"|"PLANNING"|"PLANNED"|"TRANSFORMING"|"TRANSFORMED"|"FAILED"|"COMPLETED"|"PARTIALLY_COMPLETED"|"STOPPING"|"STOPPED"|"PAUSED"|"RESUMED"|string;
  export interface TransformationStep {
    id: StepId;
    name: String;
    description: String;
    status: TransformationStepStatus;
    progressUpdates?: ProgressUpdates;
    startTime?: Timestamp;
    endTime?: Timestamp;
  }
  export type TransformationStepStatus = "CREATED"|"COMPLETED"|"PARTIALLY_COMPLETED"|"STOPPED"|"FAILED"|"PAUSED"|"SKIPPED"|string;
  export type TransformationSteps = TransformationStep[];
  export type TransformationType = "LANGUAGE_UPGRADE"|"DOCUMENT_GENERATION"|string;
  export type TransformationUploadArtifactType = "Dependencies"|"ClientBuildResult"|string;
  export interface TransformationUploadContext {
    jobId: TransformationJobId;
    uploadArtifactType: TransformationUploadArtifactType;
  }
  export type TransformationUserActionStatus = "COMPLETED"|"REJECTED"|string;
  export type UUID = string;
  export interface UploadContext {
    taskAssistPlanningUploadContext?: TaskAssistPlanningUploadContext;
    transformationUploadContext?: TransformationUploadContext;
    codeAnalysisUploadContext?: CodeAnalysisUploadContext;
    codeFixUploadContext?: CodeFixUploadContext;
    workspaceContextUploadContext?: WorkspaceContextUploadContext;
  }
  export type UploadId = string;
  export type UploadIntent = "TRANSFORMATION"|"TASK_ASSIST_PLANNING"|"AUTOMATIC_FILE_SECURITY_SCAN"|"FULL_PROJECT_SECURITY_SCAN"|"UNIT_TESTS_GENERATION"|"CODE_FIX_GENERATION"|"WORKSPACE_CONTEXT"|string;
  export type Url = string;
  export interface UserContext {
    ideCategory: IdeCategory;
    operatingSystem: OperatingSystem;
    product: UserContextProductString;
    clientId?: UUID;
    ideVersion?: String;
  }
  export type UserContextProductString = string;
  export interface UserInputMessage {
    content: UserInputMessageContentString;
    userInputMessageContext?: UserInputMessageContext;
    userIntent?: UserIntent;
    origin?: Origin;
    images?: ImageBlocks;
  }
  export type UserInputMessageContentString = string;
  export interface UserInputMessageContext {
    editorState?: EditorState;
    shellState?: ShellState;
    gitState?: GitState;
    envState?: EnvState;
    appStudioContext?: AppStudioState;
    diagnostic?: Diagnostic;
    consoleState?: ConsoleState;
    userSettings?: UserSettings;
    additionalContext?: AdditionalContentList;
    toolResults?: ToolResults;
    tools?: Tools;
  }
  export type UserIntent = "SUGGEST_ALTERNATE_IMPLEMENTATION"|"APPLY_COMMON_BEST_PRACTICES"|"IMPROVE_CODE"|"SHOW_EXAMPLES"|"CITE_SOURCES"|"EXPLAIN_LINE_BY_LINE"|"EXPLAIN_CODE_SELECTION"|"GENERATE_CLOUDFORMATION_TEMPLATE"|"GENERATE_UNIT_TESTS"|"CODE_GENERATION"|string;
  export interface UserModificationEvent {
    sessionId: UUID;
    requestId: UUID;
    programmingLanguage: ProgrammingLanguage;
    modificationPercentage: Double;
    customizationArn?: CustomizationArn;
    timestamp: Timestamp;
    acceptedCharacterCount: PrimitiveInteger;
    unmodifiedAcceptedCharacterCount: PrimitiveInteger;
  }
  export interface UserSettings {
    hasConsentedToCrossRegionCalls?: Boolean;
  }
  export interface UserTriggerDecisionEvent {
    sessionId: UUID;
    requestId: UUID;
    customizationArn?: CustomizationArn;
    programmingLanguage: ProgrammingLanguage;
    completionType: CompletionType;
    suggestionState: SuggestionState;
    recommendationLatencyMilliseconds: Double;
    timestamp: Timestamp;
    triggerToResponseLatencyMilliseconds?: Double;
    suggestionReferenceCount?: PrimitiveInteger;
    generatedLine?: PrimitiveInteger;
    numberOfRecommendations?: PrimitiveInteger;
    perceivedLatencyMilliseconds?: Double;
    acceptedCharacterCount?: PrimitiveInteger;
    addedIdeDiagnostics?: IdeDiagnosticList;
    removedIdeDiagnostics?: IdeDiagnosticList;
  }
  export interface WorkspaceContext {
    toggle: OptInFeatureToggle;
  }
  export interface WorkspaceContextUploadContext {
    workspaceId: UUID;
    relativePath: SensitiveString;
    programmingLanguage: ProgrammingLanguage;
  }
  export type WorkspaceFolderList = WorkspaceFolderListMemberString[];
  export type WorkspaceFolderListMemberString = string;
  export type WorkspaceList = WorkspaceMetadata[];
  export interface WorkspaceMetadata {
    workspaceId: UUID;
    workspaceStatus: WorkspaceStatus;
    environmentId?: SensitiveString;
  }
  export interface WorkspaceState {
    uploadId: UploadId;
    programmingLanguage: ProgrammingLanguage;
    contextTruncationScheme?: ContextTruncationScheme;
  }
  export type WorkspaceStatus = "CREATED"|"PENDING"|"READY"|"CONNECTED"|"DELETING"|string;
  export type timeBetweenChunks = Double[];
  /**
   * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
   */
  export type apiVersion = "2022-11-11"|"latest"|string;
  export interface ClientApiVersions {
    /**
     * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
     */
    apiVersion?: apiVersion;
  }
  export type ClientConfiguration = ServiceConfigurationOptions & ClientApiVersions;
  /**
   * Contains interfaces for use with the FeatureDevProxyClient client.
   */
  export import Types = FeatureDevProxyClient;
}
export = FeatureDevProxyClient;

    