version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - apt-get update
      - apt-get install -y libgtk-3-dev libxss1 xvfb 
      - apt-get install -y libnss3-dev libasound2
      - apt-get install -y libasound2-plugins
  build:
    commands:
      - npm install --unsafe-perm
      - npm run compile
      - xvfb-run npm run test
      - cp ./extension-readme.md ./README.md
      - npm run package
artifacts:
  files:
    - aws-toolkit-vscode*
    - package.json
  discard-paths: true