version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  build:
    commands:
      # pull in the build artifacts
      - cp -r ${CODEBUILD_SRC_DIR_buildPipeline}/* .
      - |
        if [ $STAGE != "prod" ]; then
          echo "Stage is not production, skipping publish step"
          exit 0
        fi
        UPLOAD_TARGET=$(ls aws-toolkit-vscode*.vsix)
        npx vsce publish --pat $VS_MARKETPLACE_PAT --packagePath $UPLOAD_TARGET
