version: 0.2

#cache:
#  paths:
#    - 'gradle-home/caches/**/*'
#    - 'gradle-home/wrapper/**/*'

env:
  variables:
    CI: true
    RECORD_UI: true
    LOCAL_ENV_RUN: true
    GRADLE_USER_HOME: gradle-home

phases:
  install:
    runtime-versions:
      java: openjdk11
      dotnet: 2.2

    commands:
      - apt-get update
      - apt-get install -y xvfb icewm procps ffmpeg libswt-gtk-3-java mono-complete
      - mkdir -p /tmp/.aws
      - aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name ui-test > /tmp/.aws/creds.json
      - |
        >/tmp/.aws/credentials echo "[default]
        aws_access_key_id=`jq -r '.Credentials.AccessKeyId' /tmp/.aws/creds.json`
        aws_secret_access_key=`jq -r '.Credentials.SecretAccessKey' /tmp/.aws/creds.json`
        aws_session_token=`jq -r '.Credentials.SessionToken' /tmp/.aws/creds.json`"
      - pip install --user aws-sam-cli

  build:
    commands:
      - Xvfb :99 -screen 0 1920x1080x24 &
      - export DISPLAY=:99
      - while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 0.1; done
      - icewm &
      - export SAM_CLI_EXEC=$(python -m site --user-base)/bin/sam
      - chmod +x gradlew
      - ./gradlew buildPlugin --console plain --info
      - >
        if [ "$RECORD_UI" ]; then
        ffmpeg -loglevel warning -f x11grab -video_size 1920x1080 -i :99 -codec:v libx264 -r 12 /tmp/screen_recording.mp4 &
        fi
      - ./gradlew guiTest coverageReport --console plain --info

  post_build:
    commands:
      - TEST_ARTIFACTS="/tmp/testArtifacts"
      - mkdir -p $TEST_ARTIFACTS/test-reports
      - rsync -r guitest.log $TEST_ARTIFACTS/gui/ || true
      - rsync -rmq --include='*/' --include '**/build/idea-sandbox/system*/log/**' --exclude='*' . $TEST_ARTIFACTS/ || true
      - rsync -rmq --include='*/' --include '**/build/reports/**' --exclude='*' . $TEST_ARTIFACTS/ || true
      - rsync -rmq --include='*/' --include '**/test-results/**/*.xml' --exclude='*' . $TEST_ARTIFACTS/test-reports || true

      - if [ "$RECORD_UI" ]; then pkill -2 ffmpeg; while pgrep ffmpeg > /dev/null; do sleep 1; done; fi
      - if [ "$RECORD_UI" ]; then cp /tmp/screen_recording.mp4 $TEST_ARTIFACTS/gui/; fi

      - VCS_COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - CI_BUILD_URL=$(echo $CODEBUILD_BUILD_URL | sed 's/#/%23/g') # Encode `#` in the URL because otherwise the url is clipped in the Codecov.io site
      - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"
      - test -n "$CODE_COV_TOKEN" && curl -s https://codecov.io/bash > codecov.sh || true # this sometimes times out but we don't want to fail the build
      - test -n "$CODE_COV_TOKEN" && test -n "$CODEBUILD_BUILD_SUCCEEDING" && bash ./codecov.sh -t $CODE_COV_TOKEN -F uitest || true

reports:
  ui-test:
    files:
      - "**/*"
    base-directory: /tmp/testArtifacts/test-reports
    discard-paths: yes

artifacts:
  base-directory: /tmp/testArtifacts
  files:
    - "**/*"
