version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10

    pre_build:
        commands:
            - npm install --unsafe-perm

    build:
        commands:
            - npm run testCompile
            - npm run lint
            - xvfb-run npm test --silent
            - VCS_COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
            - CI_BUILD_URL=$(echo $CODEBUILD_BUILD_URL | sed 's/#/%23/g') # Encode `#` in the URL because otherwise the url is clipped in the Codecov.io site
            - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"
            - curl -s https://codecov.io/bash > codecov.sh || true # this sometimes times out but we don't want to fail the build
            - if [ "$CODE_COV_TOKEN" ]; then bash ./codecov.sh -t $CODE_COV_TOKEN || true; fi
