version: 0.2

# Run unprivileged for most phases (except those marked "run-as: root").
run-as: codebuild-user

env:
    # For "pipefail".
    shell: bash
    variables:
        AWS_TOOLKIT_TEST_NO_COLOR: '1'

phases:
    install:
        run-as: root
        runtime-versions:
            nodejs: 16
        commands:
            - bash buildspec/shared/linux-install.sh

    pre_build:
        commands:
            - export HOME=/home/codebuild-user
            - bash buildspec/shared/linux-pre_build.sh

    build:
        commands:
            - export HOME=/home/codebuild-user
            # TODO: remove this after lint.yml is enabled in codebuild.
            - |
                if [ "$VSCODE_TEST_VERSION" = 'insiders' ] ; then
                    npm run testCompile
                    npm run lint
                fi
            - |
                {
                    # Ensure that "foo | run_and_report" fails correctly.
                    set -o pipefail
                    . buildspec/shared/common.sh
                    2>&1 xvfb-run npm test --silent | run_and_report 2 \
                        'rejected promise not handled' \
                        'This typically indicates a bug. Read https://developer.mozilla.org/docs/Web/JavaScript/Guide/Using_promises#error_handling'
                }
            - VCS_COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
            - CI_BUILD_URL=$(echo $CODEBUILD_BUILD_URL | sed 's/#/%23/g') # Encode `#` in the URL because otherwise the url is clipped in the Codecov.io site
            - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"

reports:
    unit-test:
        files:
            - '*'
        base-directory: '.test-reports'
