version: 0.2

# Run unprivileged for most phases (except those marked "run-as: root").
run-as: codebuild-user

env:
    variables:
        AWS_TOOLKIT_TEST_USER_DIR: '/tmp/'
        # needed or else webpack will cause it to run out of memory
        NODE_OPTIONS: '--max-old-space-size=8192'

phases:
    install:
        run-as: root
        runtime-versions:
            nodejs: 16
        commands:
            - bash buildspec/shared/linux-install.sh

    pre_build:
        commands:
            - export HOME=/home/codebuild-user
            - bash buildspec/shared/linux-pre_build.sh

    build:
        commands:
            - export HOME=/home/codebuild-user
            # Generate CHANGELOG.md
            - npm run createRelease
            - npm run package

artifacts:
    files:
        - aws-toolkit-vscode*vsix
    discard-paths: true
