version: 0.2

# Run unprivileged for most phases (except those marked "run-as: root").
run-as: codebuild-user

env:
    variables:
        AWS_TOOLKIT_TEST_USER_DIR: '/tmp/'
        # needed or else webpack will cause it to run out of memory
        NODE_OPTIONS: '--max-old-space-size=8192'
        # VSCODE_RIPGREP_TOKEN will be set in pre_build phase

phases:
    install:
        run-as: root
        runtime-versions:
            nodejs: 18
        commands:
            - bash buildspec/shared/linux-install.sh

    pre_build:
        commands:
            - export HOME=/home/codebuild-user
            # Set up VSCODE_RIPGREP_TOKEN for GitHub API access
            - export VSCODE_RIPGREP_TOKEN=${GITHUB_READONLY_TOKEN}
            - echo "Setting up VSCODE_RIPGREP_TOKEN for GitHub API access"
            - bash buildspec/shared/linux-pre_build.sh

    build:
        commands:
            - export HOME=/home/codebuild-user
            # Generate CHANGELOG.md
            - npm run createRelease -w packages/toolkit -w packages/amazonq
            - npm run package -w packages/toolkit -w packages/amazonq

artifacts:
    files:
        - '*.vsix'
