version: 0.2

env:
    variables:
        # needed or else webpack will cause it to run out of memory
        NODE_OPTIONS: '--max-old-space-size=8192'

phases:
    install:
        runtime-versions:
            nodejs: 10

    pre_build:
        commands:
            # --unsafe-perm is needed because we run as root
            - npm install --unsafe-perm

    build:
        commands:
            - export AWS_TOOLKIT_TEST_USER_DIR=/tmp/
            - npm run generateNonCodeFiles
            - cp ./extension-readme.md ./README.md
            - npm run package

artifacts:
    files:
        - aws-toolkit-vscode*
    discard-paths: true
