version: 0.2

env:
    variables:
        AWS_TOOLKIT_TEST_USER_DIR: '/tmp/'
        # needed or else webpack will cause it to run out of memory
        NODE_OPTIONS: '--max-old-space-size=8192'

phases:
    install:
        runtime-versions:
            nodejs: 10

    pre_build:
        commands:
            # If present, log into CodeArtifact. Provides a nice safety net in case NPM is down.
            # Should only affect tests run through IDEs team-hosted CodeBuild.
            - |
                if [ "$TOOLKITS_CODEARTIFACT_DOMAIN" ] && [ "$TOOLKITS_CODEARTIFACT_REPO" ] && [ "$TOOLKITS_ACCOUNT_ID" ]; then
                    if aws codeartifact login --tool npm --domain "$TOOLKITS_CODEARTIFACT_DOMAIN" --domain-owner "$TOOLKITS_ACCOUNT_ID" --repository "$TOOLKITS_CODEARTIFACT_REPO" > /dev/null 2>&1; then
                        echo "Connected to CodeArtifact"
                    else
                        echo "CodeArtifact connection failed. Falling back to npm"
                    fi
                fi
            # --unsafe-perm is needed because we run as root
            - npm ci --unsafe-perm

    build:
        commands:
            - npm run generateNonCodeFiles
            - cp ./README.quickstart.vscode.md ./README.md
            - npm run package

artifacts:
    files:
        - aws-toolkit-vscode*
    discard-paths: true
