version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10

    pre_build:
        commands:
            - REPO_URL="https://$GITHUB_TOKEN@github.com/aws/aws-toolkit-vscode.git"

    build:
        commands:
            - |
                if [ $STAGE != "prod" ]; then
                  echo "Stage is not production, skipping github push step"
                  exit 0
                fi
                git remote add origin $REPO_URL
                VERSION=$(node -e "console.log(require('./package.json').version);")
                echo "pushing to github"
                git push origin --tags
                git push origin release/v$VERSION
