/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * This file was autogenerated by generateSettings.ts. Do NOT modify by hand.
 * To update this file, update the settings in the extension package.json
 * and run `npm run generateSettings` for that extension.
 */

export const amazonqSettings = {
    "amazonQ.telemetry": {},
    "amazonQ.suppressPrompts": {
        "createCredentialsProfile": {},
        "codeWhispererNewWelcomeMessage": {},
        "codeWhispererConnectionExpired": {},
        "amazonQWelcomePage": {},
        "amazonQSessionConfigurationMessage": {},
        "minIdeVersion": {},
        "ssoCacheError": {}
    },
    "amazonQ.showInlineCodeSuggestionsWithCodeReferences": {},
    "amazonQ.importRecommendationForInlineCodeSuggestions": {},
    "amazonQ.shareContentWithAWS": {},
    "amazonQ.workspaceIndex": {},
    "amazonQ.workspaceIndexWorkerThreads": {},
    "amazonQ.workspaceIndexUseGPU": {},
    "amazonQ.workspaceIndexMaxSize": {}
}

export default amazonqSettings
