/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * This file was autogenerated by generateSettings.ts. Do NOT modify by hand.
 * To update this file, update the settings in the extension package.json
 * and run `npm run generateSettings` for that extension.
 */

export const toolkitSettings = {
    "aws.profile": {},
    "aws.ecs.openTerminalCommand": {},
    "aws.iot.maxItemsPerPage": {},
    "aws.s3.maxItemsPerPage": {},
    "aws.samcli.location": {},
    "aws.samcli.lambdaTimeout": {},
    "aws.samcli.legacyDeploy": {},
    "aws.telemetry": {},
    "aws.stepfunctions.asl.format.enable": {},
    "aws.stepfunctions.asl.maxItemsComputed": {},
    "aws.ssmDocument.ssm.maxItemsComputed": {},
    "aws.cwl.limit": {},
    "aws.samcli.manuallySelectedBuckets": {},
    "aws.samcli.enableCodeLenses": {},
    "aws.suppressPrompts": {
        "apprunnerNotifyPricing": {},
        "apprunnerNotifyPause": {},
        "ecsRunCommand": {},
        "ecsRunCommandEnable": {},
        "ecsRunCommandDisable": {},
        "regionAddAutomatically": {},
        "yamlExtPrompt": {},
        "fileViewerEdit": {},
        "createCredentialsProfile": {},
        "samcliConfirmDevStack": {},
        "remoteConnected": {},
        "codeCatalystConnectionExpired": {},
        "minIdeVersion": {},
        "ssoCacheError": {}
    },
    "aws.experiments": {
        "jsonResourceModification": {}
    },
    "aws.resources.enabledResources": {},
    "aws.lambda.recentlyUploaded": {},
    "aws.accessAnalyzer.policyChecks.checkNoNewAccessFilePath": {},
    "aws.accessAnalyzer.policyChecks.checkAccessNotGrantedFilePath": {},
    "aws.accessAnalyzer.policyChecks.cloudFormationParameterFilePath": {}
}

export default toolkitSettings
