/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * This file was autogenerated by generateSettings.ts. Do NOT modify by hand.
 * To update this file, update the settings in the extension package.json
 * and run `npm run generateSettings` for that extension.
 */

export const amazonqSettings = {
    "amazonQ.telemetry": {},
    "amazonQ.suppressPrompts": {
        "createCredentialsProfile": {},
        "codeWhispererNewWelcomeMessage": {},
        "codeWhispererConnectionExpired": {},
        "amazonQWelcomePage": {},
        "amazonQSessionConfigurationMessage": {},
        "minIdeVersion": {},
        "ssoCacheError": {},
        "amazonQLspManifestMessage": {},
        "amazonQWorkspaceLspManifestMessage": {},
        "amazonQChatDisclaimer": {},
        "amazonQChatPairProgramming": {},
        "amazonQSelectDeveloperProfile": {}
    },
    "amazonQ.showCodeWithReferences": {},
    "amazonQ.allowFeatureDevelopmentToRunCodeAndTests": {},
    "amazonQ.importRecommendationForInlineCodeSuggestions": {},
    "amazonQ.shareContentWithAWS": {},
    "amazonQ.server-sideContext": {},
    "amazonQ.workspaceIndex": {},
    "amazonQ.workspaceIndexWorkerThreads": {},
    "amazonQ.workspaceIndexUseGPU": {},
    "amazonQ.workspaceIndexMaxSize": {},
    "amazonQ.workspaceIndexMaxFileSize": {},
    "amazonQ.workspaceIndexCacheDirPath": {},
    "amazonQ.workspaceIndexIgnoreFilePatterns": {},
    "amazonQ.ignoredSecurityIssues": {},
    "amazonQ.proxy.certificateAuthority": {}
}

export default amazonqSettings
