Resources:
    SourceCodeTwoFoldersDeep:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: src/subfolder/app.handlerTwoFoldersDeep
            Runtime: nodejs14.x
