#!/bin/bash

# Usage:
#   AWS_REGION=… AWS_MDE_ENDPOINT=… AWS_SSM_CLI=… AWS_MDE_SESSION=… AWS_MDE_STREAMURL=… AWS_MDE_TOKEN=… ./mde_connect <env-id>

set -e
set -u

_DATE_CMD=true

if command > /dev/null 2>&1 -v date; then
    _DATE_CMD=date
elif command > /dev/null 2>&1 -v /bin/date; then
    _DATE_CMD=/bin/date
fi

_log() {
    # >&2 echo "$@"
    echo "$("$_DATE_CMD" '+%Y%m%d')" "$@"
}

_require_nolog() {
    if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
        _log "error: missing required arg: $1"
        exit 1
    fi
}

_require() {
    _require_nolog "$@"
    _log "$1=$2"
}

_main() {
    _HOST="${1:-}"

    _log "=============================================================================="
    _require AWS_MDE_ENDPOINT "${AWS_MDE_ENDPOINT:-}"
    _require AWS_REGION "${AWS_REGION:-}"
    _require AWS_SSM_CLI "${AWS_SSM_CLI:-}"
    _require AWS_MDE_SESSION "${AWS_MDE_SESSION:-}"
    _require_nolog AWS_MDE_STREAMURL "${AWS_MDE_STREAMURL:-}"
    _require_nolog AWS_MDE_TOKEN "${AWS_MDE_TOKEN:-}"

    exec "$AWS_SSM_CLI" \
        "{\"streamUrl\":\"$AWS_MDE_STREAMURL\",\"tokenValue\":\"$AWS_MDE_TOKEN\",\"sessionId\":\"$AWS_MDE_SESSION\"}" \
        "$AWS_REGION" \
        "StartSession"
}

_main "${1:-}"
