<script setup lang="ts">
/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { computed, reactive } from 'vue'
import TkSpaceBetween from './tkSpaceBetween.vue'
import TkBox from './tkBox.vue'

//-------------------------------------------------------------------------------------------------
// Props
//-------------------------------------------------------------------------------------------------
interface Props {
    itemsPerPage: number
    totalItems: number
}

const props = withDefaults(defineProps<Props>(), {})

//-------------------------------------------------------------------------------------------------
// State
//-------------------------------------------------------------------------------------------------
interface State {
    paginatedPage: number
}

const state: State = reactive({
    paginatedPage: 0,
})

//-------------------------------------------------------------------------------------------------
// Emitted Events
//-------------------------------------------------------------------------------------------------
const emit = defineEmits<{
    (e: 'pagination', page: number): void
}>()

//-------------------------------------------------------------------------------------------------
// Computed Properties
//-------------------------------------------------------------------------------------------------
const paginationLabel = computed(() => {
    const start = state.paginatedPage * props.itemsPerPage + 1
    let end = start + props.itemsPerPage - 1

    if (end > props.totalItems) {
        end = props.totalItems
    }

    return `${start} - ${end} of ${props.totalItems}`
})

const leftPaginationDisabled = computed(() => {
    if (props.totalItems <= props.itemsPerPage || state.paginatedPage === 0) {
        return true
    }

    return false
})

const rightPaginationDisabled = computed(() => {
    if (props.totalItems <= props.itemsPerPage || (state.paginatedPage + 1) * props.itemsPerPage >= props.totalItems) {
        return true
    }

    return false
})

//-------------------------------------------------------------------------------------------------
// Variables & Methods
//-------------------------------------------------------------------------------------------------
function onLeftPagination(): void {
    state.paginatedPage -= 1
    emit('pagination', state.paginatedPage)
}

function onRightPagination(): void {
    state.paginatedPage += 1
    emit('pagination', state.paginatedPage)
}
</script>

<template>
    <tk-space-between>
        <table class="tk-table">
            <thead class="tk-table-head">
                <tr>
                    <slot name="head"></slot>
                </tr>
            </thead>
            <tbody class="tk-table-body">
                <slot name="body"></slot>
            </tbody>
        </table>

        <tk-box float="right">
            <tk-space-between class="tk-table-pagination" direction="horizontal">
                <div>{{ paginationLabel }}</div>
                <button :disabled="leftPaginationDisabled" @click="onLeftPagination" aria-label="Previous page">
                    &lt;
                </button>
                <button :disabled="rightPaginationDisabled" @click="onRightPagination" aria-label="Next page">
                    &gt;
                </button>
            </tk-space-between>
        </tk-box>
    </tk-space-between>
</template>

<!-- Below global styles apply to slot content generated by parent component. This is needed because Vue scoped styles do not apply to slot content generated by parent. -->
<style>
.tk-table th,
.tk-table td {
    text-align: left;
    border-bottom: 1px solid var(--vscode-settings-headerBorder);
    padding-top: 10px;
    padding-bottom: 10px;
}

.tk-table th {
    color: var(--vscode-settings-headerForeground);
    padding-top: 0;
}
</style>

<style scoped>
.tk-table {
    border-collapse: collapse;
    width: 100%;
}

.tk-table-pagination > button {
    background: none;
    border: none;
    color: var(--vscode-button-background);
    cursor: pointer;
    font-size: 18px;
    padding: 0px 4px;
}

.tk-table-pagination > button:disabled {
    color: unset;
    cursor: unset;
}

.tk-table-pagination > button:focus {
    outline: none;
}
</style>
