/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import path from 'path'
import { commands, Position, TextEditor, Uri, window, workspace } from 'vscode'
import { getLogger } from '../../../shared/logger'
import { randomUUID } from '../../../common/crypto'

export class EditorContentController {
    public insertTextAtCursorPosition(
        text: string,
        trackCodeEdit: (editor: TextEditor, cursorStart: Position) => void
    ) {
        const editor = window.activeTextEditor
        if (editor) {
            const cursorStart = editor.selection.active
            editor
                .edit((editBuilder) => {
                    editBuilder.insert(cursorStart, text)
                })
                .then(
                    (appliedEdits) => {
                        if (appliedEdits) {
                            trackCodeEdit(editor, cursorStart)
                        }
                    },
                    (e) => {
                        getLogger().error('TextEditor.edit failed: %s', (e as Error).message)
                    }
                )
        }
    }

    public async acceptDiff(message: any) {
        const { filePath } = message?.context?.activeFileContext || {}
        if (filePath && message?.code?.trim().length > 0) {
            const right = Uri.file(filePath) // Existing File to Write
            const fileName = path.basename(right.path)

            const diffScheme = 'amazon-q-accept-diff'
            const left = Uri.parse(`${diffScheme}:${fileName}-` + randomUUID())
            class LeftContentProvider {
                provideTextDocumentContent(_uri: Uri) {
                    return message.code
                }
            }
            const leftContentProvider = new LeftContentProvider()
            void workspace.registerTextDocumentContentProvider(diffScheme, leftContentProvider)

            await commands.executeCommand('vscode.diff', left, right, `${fileName} (Generated by Amazon Q)`)
        }
    }
}
