/*!
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import * as vscode from 'vscode'

/**
 * This file emits the Program.cs file contents from the stock SAM CLI app for dotnet, as well as
 * the corresponding DocumentSymbols generated by VS Code.
 */

export function getDocumentSymbols(): vscode.DocumentSymbol[] {
    const namespaceSymbol: vscode.DocumentSymbol = new vscode.DocumentSymbol(
        'HelloWorld',
        '',
        vscode.SymbolKind.Namespace,
        new vscode.Range(14, 0, 51, 1),
        new vscode.Range(14, 10, 14, 20)
    )
    const classSymbol: vscode.DocumentSymbol = new vscode.DocumentSymbol(
        'HelloWorld.Function',
        '',
        vscode.SymbolKind.Class,
        new vscode.Range(17, 4, 50, 5),
        new vscode.Range(17, 17, 17, 25)
    )
    const privateMethodSymbol: vscode.DocumentSymbol = new vscode.DocumentSymbol(
        'GetCallingIP()',
        '',
        vscode.SymbolKind.Method,
        new vscode.Range(22, 8, 31, 9),
        new vscode.Range(22, 42, 22, 54)
    )
    const publicMethodSymbol: vscode.DocumentSymbol = new vscode.DocumentSymbol(
        'FunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)',
        '',
        vscode.SymbolKind.Method,
        new vscode.Range(33, 8, 49, 9),
        new vscode.Range(33, 39, 33, 54)
    )

    namespaceSymbol.children.push(classSymbol)
    classSymbol.children.push(privateMethodSymbol)
    classSymbol.children.push(publicMethodSymbol)

    return [namespaceSymbol]
}

export function getFunctionText(): string {
    return String.raw`
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace HelloWorld
{

    public class Function
    {

        private static readonly HttpClient client = new HttpClient();

        private static async Task<string> GetCallingIP()
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Add("User-Agent", "AWS Lambda .Net Client");

            var msg = await client.GetStringAsync("http://checkip.amazonaws.com/").ConfigureAwait(continueOnCapturedContext:false);

            return msg.Replace("\n","");
        }

        public async Task<APIGatewayProxyResponse> FunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
        {

            var location = await GetCallingIP();
            var body = new Dictionary<string, string>
            {
                { "message", "hello world" },
                { "location", location }
            };

            return new APIGatewayProxyResponse
            {
                Body = JsonSerializer.Serialize(body),
                StatusCode = 200,
                Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
            };
        }
    }
}
`
}
