
/**
 * THIS FILE IS AUTOGENERATED BY 'generateServiceClient.ts'.
 * DO NOT EDIT BY HAND.
 */

import {Request} from 'aws-sdk/lib/request';
import {Response} from 'aws-sdk/lib/response';
import {AWSError} from 'aws-sdk/lib/error';
import {Service} from 'aws-sdk/lib/service';
import {ServiceConfigurationOptions} from 'aws-sdk/lib/service';
import {ConfigBase as Config} from 'aws-sdk/lib/config-base';
interface Blob {}
declare class CodeWhispererUserClient extends Service {
  /**
   * Constructs a service object. This object has one method for each API operation.
   */
  constructor(options?: CodeWhispererUserClient.Types.ClientConfiguration)
  config: Config & CodeWhispererUserClient.Types.ClientConfiguration;
  /**
   * 
   */
  createArtifactUploadUrl(params: CodeWhispererUserClient.Types.CreateUploadUrlRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.CreateUploadUrlResponse) => void): Request<CodeWhispererUserClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createArtifactUploadUrl(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.CreateUploadUrlResponse) => void): Request<CodeWhispererUserClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createTaskAssistConversation(params: CodeWhispererUserClient.Types.CreateTaskAssistConversationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.CreateTaskAssistConversationResponse) => void): Request<CodeWhispererUserClient.Types.CreateTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  createTaskAssistConversation(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.CreateTaskAssistConversationResponse) => void): Request<CodeWhispererUserClient.Types.CreateTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  createUploadUrl(params: CodeWhispererUserClient.Types.CreateUploadUrlRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.CreateUploadUrlResponse) => void): Request<CodeWhispererUserClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  createUploadUrl(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.CreateUploadUrlResponse) => void): Request<CodeWhispererUserClient.Types.CreateUploadUrlResponse, AWSError>;
  /**
   * 
   */
  deleteTaskAssistConversation(params: CodeWhispererUserClient.Types.DeleteTaskAssistConversationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.DeleteTaskAssistConversationResponse) => void): Request<CodeWhispererUserClient.Types.DeleteTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  deleteTaskAssistConversation(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.DeleteTaskAssistConversationResponse) => void): Request<CodeWhispererUserClient.Types.DeleteTaskAssistConversationResponse, AWSError>;
  /**
   * 
   */
  generateCompletions(params: CodeWhispererUserClient.Types.GenerateCompletionsRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GenerateCompletionsResponse) => void): Request<CodeWhispererUserClient.Types.GenerateCompletionsResponse, AWSError>;
  /**
   * 
   */
  generateCompletions(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GenerateCompletionsResponse) => void): Request<CodeWhispererUserClient.Types.GenerateCompletionsResponse, AWSError>;
  /**
   * 
   */
  getCodeAnalysis(params: CodeWhispererUserClient.Types.GetCodeAnalysisRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetCodeAnalysisResponse) => void): Request<CodeWhispererUserClient.Types.GetCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  getCodeAnalysis(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetCodeAnalysisResponse) => void): Request<CodeWhispererUserClient.Types.GetCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  getTaskAssistCodeGeneration(params: CodeWhispererUserClient.Types.GetTaskAssistCodeGenerationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetTaskAssistCodeGenerationResponse) => void): Request<CodeWhispererUserClient.Types.GetTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  getTaskAssistCodeGeneration(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetTaskAssistCodeGenerationResponse) => void): Request<CodeWhispererUserClient.Types.GetTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  getTransformation(params: CodeWhispererUserClient.Types.GetTransformationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetTransformationResponse) => void): Request<CodeWhispererUserClient.Types.GetTransformationResponse, AWSError>;
  /**
   * 
   */
  getTransformation(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetTransformationResponse) => void): Request<CodeWhispererUserClient.Types.GetTransformationResponse, AWSError>;
  /**
   * 
   */
  getTransformationPlan(params: CodeWhispererUserClient.Types.GetTransformationPlanRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetTransformationPlanResponse) => void): Request<CodeWhispererUserClient.Types.GetTransformationPlanResponse, AWSError>;
  /**
   * 
   */
  getTransformationPlan(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.GetTransformationPlanResponse) => void): Request<CodeWhispererUserClient.Types.GetTransformationPlanResponse, AWSError>;
  /**
   * 
   */
  listAvailableCustomizations(params: CodeWhispererUserClient.Types.ListAvailableCustomizationsRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.ListAvailableCustomizationsResponse) => void): Request<CodeWhispererUserClient.Types.ListAvailableCustomizationsResponse, AWSError>;
  /**
   * 
   */
  listAvailableCustomizations(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.ListAvailableCustomizationsResponse) => void): Request<CodeWhispererUserClient.Types.ListAvailableCustomizationsResponse, AWSError>;
  /**
   * 
   */
  listCodeAnalysisFindings(params: CodeWhispererUserClient.Types.ListCodeAnalysisFindingsRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.ListCodeAnalysisFindingsResponse) => void): Request<CodeWhispererUserClient.Types.ListCodeAnalysisFindingsResponse, AWSError>;
  /**
   * 
   */
  listCodeAnalysisFindings(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.ListCodeAnalysisFindingsResponse) => void): Request<CodeWhispererUserClient.Types.ListCodeAnalysisFindingsResponse, AWSError>;
  /**
   * 
   */
  listFeatureEvaluations(params: CodeWhispererUserClient.Types.ListFeatureEvaluationsRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.ListFeatureEvaluationsResponse) => void): Request<CodeWhispererUserClient.Types.ListFeatureEvaluationsResponse, AWSError>;
  /**
   * 
   */
  listFeatureEvaluations(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.ListFeatureEvaluationsResponse) => void): Request<CodeWhispererUserClient.Types.ListFeatureEvaluationsResponse, AWSError>;
  /**
   * 
   */
  sendTelemetryEvent(params: CodeWhispererUserClient.Types.SendTelemetryEventRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.SendTelemetryEventResponse) => void): Request<CodeWhispererUserClient.Types.SendTelemetryEventResponse, AWSError>;
  /**
   * 
   */
  sendTelemetryEvent(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.SendTelemetryEventResponse) => void): Request<CodeWhispererUserClient.Types.SendTelemetryEventResponse, AWSError>;
  /**
   * 
   */
  startCodeAnalysis(params: CodeWhispererUserClient.Types.StartCodeAnalysisRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StartCodeAnalysisResponse) => void): Request<CodeWhispererUserClient.Types.StartCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  startCodeAnalysis(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StartCodeAnalysisResponse) => void): Request<CodeWhispererUserClient.Types.StartCodeAnalysisResponse, AWSError>;
  /**
   * 
   */
  startTaskAssistCodeGeneration(params: CodeWhispererUserClient.Types.StartTaskAssistCodeGenerationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StartTaskAssistCodeGenerationResponse) => void): Request<CodeWhispererUserClient.Types.StartTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  startTaskAssistCodeGeneration(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StartTaskAssistCodeGenerationResponse) => void): Request<CodeWhispererUserClient.Types.StartTaskAssistCodeGenerationResponse, AWSError>;
  /**
   * 
   */
  startTransformation(params: CodeWhispererUserClient.Types.StartTransformationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StartTransformationResponse) => void): Request<CodeWhispererUserClient.Types.StartTransformationResponse, AWSError>;
  /**
   * 
   */
  startTransformation(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StartTransformationResponse) => void): Request<CodeWhispererUserClient.Types.StartTransformationResponse, AWSError>;
  /**
   * 
   */
  stopTransformation(params: CodeWhispererUserClient.Types.StopTransformationRequest, callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StopTransformationResponse) => void): Request<CodeWhispererUserClient.Types.StopTransformationResponse, AWSError>;
  /**
   * 
   */
  stopTransformation(callback?: (err: AWSError, data: CodeWhispererUserClient.Types.StopTransformationResponse) => void): Request<CodeWhispererUserClient.Types.StopTransformationResponse, AWSError>;
}
declare namespace CodeWhispererUserClient {
  export type ArtifactMap = {[key: string]: UploadId};
  export type ArtifactType = "SourceCode"|"BuiltJars"|string;
  export interface AssistantResponseMessage {
    messageId?: MessageId;
    content: AssistantResponseMessageContentString;
    supplementaryWebLinks?: SupplementaryWebLinks;
    references?: References;
    followupPrompt?: FollowupPrompt;
  }
  export type AssistantResponseMessageContentString = string;
  export type Base64EncodedPaginationToken = string;
  export type Boolean = boolean;
  export interface ChatAddMessageEvent {
    conversationId: ConversationId;
    messageId: MessageId;
    userIntent?: UserIntent;
    hasCodeSnippet?: Boolean;
    programmingLanguage?: ProgrammingLanguage;
    activeEditorTotalCharacters?: Integer;
    timeToFirstChunkMilliseconds?: Double;
    timeBetweenChunks?: TimeBetweenChunks;
    fullResponselatency?: Double;
    requestLength?: Integer;
    responseLength?: Integer;
  }
  export type ChatHistory = ChatMessage[];
  export interface ChatInteractWithMessageEvent {
    conversationId: ConversationId;
    messageId: MessageId;
    interactionType?: ChatMessageInteractionType;
    interactionTarget?: String;
    acceptedCharacterCount?: Integer;
    acceptedSnippetHasReference?: Boolean;
  }
  export interface ChatMessage {
    userInputMessage?: UserInputMessage;
    assistantResponseMessage?: AssistantResponseMessage;
  }
  export type ChatMessageInteractionType = "INSERT_AT_CURSOR"|"COPY_SNIPPET"|"COPY"|"CLICK_LINK"|"CLICK_BODY_LINK"|"CLICK_FOLLOW_UP"|"HOVER_REFERENCE"|"UPVOTE"|"DOWNVOTE"|string;
  export interface ChatUserModificationEvent {
    conversationId: ConversationId;
    messageId: MessageId;
    programmingLanguage?: ProgrammingLanguage;
    modificationPercentage: Double;
  }
  export type ChatTriggerType = "MANUAL"|"DIAGNOSTIC"|string;
  export type CodeAnalysisFindingsSchema = "codeanalysis/findings/1.0"|string;
  export type CodeAnalysisStatus = "Completed"|"Pending"|"Failed"|string;
  export interface CodeCoverageEvent {
    customizationArn?: CustomizationArn;
    programmingLanguage: ProgrammingLanguage;
    acceptedCharacterCount: PrimitiveInteger;
    totalCharacterCount: PrimitiveInteger;
    timestamp: Timestamp;
    unmodifiedAcceptedCharacterCount?: PrimitiveInteger;
  }
  export type CodeGenerationId = string;
  export interface CodeGenerationStatus {
    status: CodeGenerationWorkflowStatus;
    currentStage: CodeGenerationWorkflowStage;
  }
  export type CodeGenerationWorkflowStage = "InitialCodeGeneration"|"CodeRefinement"|string;
  export type CodeGenerationWorkflowStatus = "InProgress"|"Complete"|"Failed"|string;
  export interface CodeScanEvent {
    programmingLanguage: ProgrammingLanguage;
    codeScanJobId: CodeScanJobId;
    timestamp: Timestamp;
  }
  export type CodeScanJobId = string;
  export interface Completion {
    content: CompletionContentString;
    references?: References;
    mostRelevantMissingImports?: Imports;
  }
  export type CompletionContentString = string;
  export type CompletionType = "BLOCK"|"LINE"|string;
  export type Completions = Completion[];
  export type ContentChecksumType = "SHA_256"|string;
  export type ContextTruncationScheme = "ANALYSIS"|"GUMBY"|string;
  export type ConversationId = string;
  export interface ConversationState {
    conversationId?: ConversationId;
    history?: ChatHistory;
    currentMessage: ChatMessage;
    chatTriggerType: ChatTriggerType;
  }
  export interface CreateTaskAssistConversationRequest {
  }
  export interface CreateTaskAssistConversationResponse {
    conversationId: ConversationId;
  }
  export interface CreateUploadUrlRequest {
    contentMd5?: CreateUploadUrlRequestContentMd5String;
    contentChecksum?: CreateUploadUrlRequestContentChecksumString;
    contentChecksumType?: ContentChecksumType;
    contentLength?: CreateUploadUrlRequestContentLengthLong;
    artifactType?: ArtifactType;
    uploadIntent?: UploadIntent;
    uploadContext?: UploadContext;
  }
  export type CreateUploadUrlRequestContentChecksumString = string;
  export type CreateUploadUrlRequestContentLengthLong = number;
  export type CreateUploadUrlRequestContentMd5String = string;
  export interface CreateUploadUrlResponse {
    uploadId: UploadId;
    uploadUrl: PreSignedUrl;
    kmsKeyArn?: ResourceArn;
  }
  export interface CursorState {
    position?: Position;
    range?: Range;
  }
  export interface Customization {
    arn: CustomizationArn;
    name?: CustomizationName;
    description?: Description;
  }
  export type CustomizationArn = string;
  export type CustomizationName = string;
  export type Customizations = Customization[];
  export interface DeleteTaskAssistConversationRequest {
    conversationId: ConversationId;
  }
  export interface DeleteTaskAssistConversationResponse {
    conversationId: ConversationId;
  }
  export type Description = string;
  export interface Diagnostic {
    textDocumentDiagnostic?: TextDocumentDiagnostic;
    runtimeDiagnostic?: RuntimeDiagnostic;
  }
  export type DiagnosticSeverity = "ERROR"|"WARNING"|"INFORMATION"|"HINT"|string;
  export interface Dimension {
    name?: DimensionNameString;
    value?: DimensionValueString;
  }
  export type DimensionList = Dimension[];
  export type DimensionNameString = string;
  export type DimensionValueString = string;
  export interface DocumentSymbol {
    name: DocumentSymbolNameString;
    type: SymbolType;
    source?: DocumentSymbolSourceString;
  }
  export type DocumentSymbolNameString = string;
  export type DocumentSymbolSourceString = string;
  export type DocumentSymbols = DocumentSymbol[];
  export type Double = number;
  export interface EditorState {
    document?: TextDocument;
    cursorState?: CursorState;
  }
  export interface FeatureEvaluation {
    feature: FeatureName;
    variation: FeatureVariation;
    value: FeatureValue;
  }
  export type FeatureEvaluationsList = FeatureEvaluation[];
  export type FeatureName = string;
  export interface FeatureValue {
    boolValue?: Boolean;
    doubleValue?: Double;
    longValue?: Long;
    stringValue?: FeatureValueStringType;
  }
  export type FeatureValueStringType = string;
  export type FeatureVariation = string;
  export interface FileContext {
    leftFileContent: FileContextLeftFileContentString;
    rightFileContent: FileContextRightFileContentString;
    filename: FileContextFilenameString;
    programmingLanguage: ProgrammingLanguage;
  }
  export type FileContextFilenameString = string;
  export type FileContextLeftFileContentString = string;
  export type FileContextRightFileContentString = string;
  export interface FollowupPrompt {
    content: FollowupPromptContentString;
    userIntent?: UserIntent;
  }
  export type FollowupPromptContentString = string;
  export interface GenerateCompletionsRequest {
    fileContext: FileContext;
    maxResults?: GenerateCompletionsRequestMaxResultsInteger;
    nextToken?: GenerateCompletionsRequestNextTokenString;
    referenceTrackerConfiguration?: ReferenceTrackerConfiguration;
    supplementalContexts?: SupplementalContextList;
    customizationArn?: CustomizationArn;
    optOutPreference?: OptOutPreference;
    userContext?: UserContext;
  }
  export type GenerateCompletionsRequestMaxResultsInteger = number;
  export type GenerateCompletionsRequestNextTokenString = string;
  export interface GenerateCompletionsResponse {
    completions?: Completions;
    nextToken?: SensitiveString;
  }
  export interface GetCodeAnalysisRequest {
    jobId: GetCodeAnalysisRequestJobIdString;
  }
  export type GetCodeAnalysisRequestJobIdString = string;
  export interface GetCodeAnalysisResponse {
    status: CodeAnalysisStatus;
    errorMessage?: SensitiveString;
  }
  export interface GetTaskAssistCodeGenerationRequest {
    conversationId: ConversationId;
    codeGenerationId: CodeGenerationId;
  }
  export interface GetTaskAssistCodeGenerationResponse {
    conversationId: ConversationId;
    codeGenerationStatus: CodeGenerationStatus;
  }
  export interface GetTransformationPlanRequest {
    transformationJobId: TransformationJobId;
  }
  export interface GetTransformationPlanResponse {
    transformationPlan: TransformationPlan;
  }
  export interface GetTransformationRequest {
    transformationJobId: TransformationJobId;
  }
  export interface GetTransformationResponse {
    transformationJob: TransformationJob;
  }
  export type IdeCategory = "JETBRAINS"|"VSCODE"|string;
  export type IdempotencyToken = string;
  export interface Import {
    statement?: ImportStatementString;
  }
  export type ImportStatementString = string;
  export type Imports = Import[];
  export type Integer = number;
  export interface ListAvailableCustomizationsRequest {
    maxResults?: ListAvailableCustomizationsRequestMaxResultsInteger;
    nextToken?: Base64EncodedPaginationToken;
  }
  export type ListAvailableCustomizationsRequestMaxResultsInteger = number;
  export interface ListAvailableCustomizationsResponse {
    customizations: Customizations;
    nextToken?: Base64EncodedPaginationToken;
  }
  export interface ListCodeAnalysisFindingsRequest {
    jobId: ListCodeAnalysisFindingsRequestJobIdString;
    nextToken?: PaginationToken;
    codeAnalysisFindingsSchema: CodeAnalysisFindingsSchema;
  }
  export type ListCodeAnalysisFindingsRequestJobIdString = string;
  export interface ListCodeAnalysisFindingsResponse {
    nextToken?: PaginationToken;
    codeAnalysisFindings: SensitiveString;
  }
  export interface ListFeatureEvaluationsRequest {
    userContext: UserContext;
  }
  export interface ListFeatureEvaluationsResponse {
    featureEvaluations: FeatureEvaluationsList;
  }
  export type Long = number;
  export type MessageId = string;
  export interface MetricData {
    metricName: MetricDataMetricNameString;
    metricValue: Double;
    timestamp: Timestamp;
    dimensions?: DimensionList;
  }
  export type MetricDataMetricNameString = string;
  export type OperatingSystem = "MAC"|"WINDOWS"|"LINUX"|string;
  export type OptOutPreference = "OPTIN"|"OPTOUT"|string;
  export type PaginationToken = string;
  export interface Position {
    line: Integer;
    character: Integer;
  }
  export type PreSignedUrl = string;
  export type PrimitiveInteger = number;
  export interface ProgrammingLanguage {
    languageName: ProgrammingLanguageLanguageNameString;
  }
  export type ProgrammingLanguageLanguageNameString = string;
  export type ProgressUpdates = TransformationProgressUpdate[];
  export interface Range {
    start: Position;
    end: Position;
  }
  export type RecommendationsWithReferencesPreference = "BLOCK"|"ALLOW"|string;
  export interface Reference {
    licenseName?: ReferenceLicenseNameString;
    repository?: ReferenceRepositoryString;
    url?: ReferenceUrlString;
    recommendationContentSpan?: Span;
  }
  export type ReferenceLicenseNameString = string;
  export type ReferenceRepositoryString = string;
  export interface ReferenceTrackerConfiguration {
    recommendationsWithReferences: RecommendationsWithReferencesPreference;
  }
  export type ReferenceUrlString = string;
  export type References = Reference[];
  export type ResourceArn = string;
  export interface RuntimeDiagnostic {
    source: RuntimeDiagnosticSourceString;
    severity: DiagnosticSeverity;
    message: RuntimeDiagnosticMessageString;
  }
  export type RuntimeDiagnosticMessageString = string;
  export type RuntimeDiagnosticSourceString = string;
  export interface SendTelemetryEventRequest {
    clientToken?: IdempotencyToken;
    telemetryEvent: TelemetryEvent;
    optOutPreference?: OptOutPreference;
    userContext?: UserContext;
  }
  export interface SendTelemetryEventResponse {
  }
  export type SensitiveString = string;
  export interface Span {
    start?: SpanStartInteger;
    end?: SpanEndInteger;
  }
  export type SpanEndInteger = number;
  export type SpanStartInteger = number;
  export interface StartCodeAnalysisRequest {
    artifacts: ArtifactMap;
    programmingLanguage: ProgrammingLanguage;
    clientToken?: StartCodeAnalysisRequestClientTokenString;
  }
  export type StartCodeAnalysisRequestClientTokenString = string;
  export interface StartCodeAnalysisResponse {
    jobId: StartCodeAnalysisResponseJobIdString;
    status: CodeAnalysisStatus;
    errorMessage?: SensitiveString;
  }
  export type StartCodeAnalysisResponseJobIdString = string;
  export interface StartTaskAssistCodeGenerationRequest {
    conversationState: ConversationState;
    workspaceState: WorkspaceState;
  }
  export interface StartTaskAssistCodeGenerationResponse {
    conversationId: ConversationId;
    codeGenerationId: CodeGenerationId;
  }
  export interface StartTransformationRequest {
    workspaceState: WorkspaceState;
    transformationSpec: TransformationSpec;
  }
  export interface StartTransformationResponse {
    transformationJobId: TransformationJobId;
  }
  export type StepId = string;
  export interface StopTransformationRequest {
    transformationJobId: TransformationJobId;
  }
  export interface StopTransformationResponse {
    transformationStatus: TransformationStatus;
  }
  export type String = string;
  export type SuggestionState = "ACCEPT"|"REJECT"|"DISCARD"|"EMPTY"|string;
  export interface SupplementalContext {
    filePath: SupplementalContextFilePathString;
    content: SupplementalContextContentString;
  }
  export type SupplementalContextContentString = string;
  export type SupplementalContextFilePathString = string;
  export type SupplementalContextList = SupplementalContext[];
  export interface SupplementaryWebLink {
    url: SupplementaryWebLinkUrlString;
    title: SupplementaryWebLinkTitleString;
    snippet?: SupplementaryWebLinkSnippetString;
  }
  export type SupplementaryWebLinkSnippetString = string;
  export type SupplementaryWebLinkTitleString = string;
  export type SupplementaryWebLinkUrlString = string;
  export type SupplementaryWebLinks = SupplementaryWebLink[];
  export type SymbolType = "DECLARATION"|"USAGE"|string;
  export interface TaskAssistPlanningUploadContext {
    conversationId: ConversationId;
  }
  export interface TelemetryEvent {
    userTriggerDecisionEvent?: UserTriggerDecisionEvent;
    codeCoverageEvent?: CodeCoverageEvent;
    userModificationEvent?: UserModificationEvent;
    codeScanEvent?: CodeScanEvent;
    metricData?: MetricData;
    chatAddMessageEvent?: ChatAddMessageEvent;
    chatInteractWithMessageEvent?: ChatInteractWithMessageEvent;
    chatUserModificationEvent?: ChatUserModificationEvent;
  }
  export interface TextDocument {
    relativeFilePath: TextDocumentRelativeFilePathString;
    programmingLanguage?: ProgrammingLanguage;
    text?: TextDocumentTextString;
    documentSymbols?: DocumentSymbols;
  }
  export interface TextDocumentDiagnostic {
    document: TextDocument;
    range: Range;
    source: SensitiveString;
    severity: DiagnosticSeverity;
    message: TextDocumentDiagnosticMessageString;
  }
  export type TextDocumentDiagnosticMessageString = string;
  export type TextDocumentRelativeFilePathString = string;
  export type TextDocumentTextString = string;
  export type TimeBetweenChunks = Double[];
  export type Timestamp = Date;
  export interface TransformationJob {
    jobId?: TransformationJobId;
    transformationSpec?: TransformationSpec;
    status?: TransformationStatus;
    reason?: String;
    creationTime?: Timestamp;
    startExecutionTime?: Timestamp;
    endExecutionTime?: Timestamp;
  }
  export type TransformationJobId = string;
  export type TransformationLanguage = "JAVA_8"|"JAVA_11"|"JAVA_17"|string;
  export interface TransformationPlan {
    transformationSteps: TransformationSteps;
  }
  export interface TransformationProgressUpdate {
    name: String;
    status: TransformationProgressUpdateStatus;
    description?: String;
    startTime?: Timestamp;
    endTime?: Timestamp;
  }
  export type TransformationProgressUpdateStatus = "IN_PROGRESS"|"COMPLETED"|"FAILED"|string;
  export interface TransformationProjectState {
    language?: TransformationLanguage;
  }
  export interface TransformationSpec {
    transformationType?: TransformationType;
    source?: TransformationProjectState;
    target?: TransformationProjectState;
  }
  export type TransformationStatus = "CREATED"|"ACCEPTED"|"REJECTED"|"STARTED"|"PREPARING"|"PREPARED"|"PLANNING"|"PLANNED"|"TRANSFORMING"|"TRANSFORMED"|"FAILED"|"COMPLETED"|"PARTIALLY_COMPLETED"|"STOPPING"|"STOPPED"|string;
  export interface TransformationStep {
    id: StepId;
    name: String;
    description: String;
    status: TransformationStepStatus;
    progressUpdates?: ProgressUpdates;
    startTime?: Timestamp;
    endTime?: Timestamp;
  }
  export type TransformationStepStatus = "CREATED"|"COMPLETED"|"PARTIALLY_COMPLETED"|"STOPPED"|"FAILED"|string;
  export type TransformationSteps = TransformationStep[];
  export type TransformationType = "LANGUAGE_UPGRADE"|string;
  export type UUID = string;
  export interface UploadContext {
    taskAssistPlanningUploadContext?: TaskAssistPlanningUploadContext;
  }
  export type UploadId = string;
  export type UploadIntent = "TRANSFORMATION"|"TASK_ASSIST_PLANNING"|string;
  export interface UserContext {
    ideCategory: IdeCategory;
    operatingSystem: OperatingSystem;
    product: UserContextProductString;
    clientId?: UUID;
    ideVersion?: String;
  }
  export type UserContextProductString = string;
  export interface UserInputMessage {
    content: UserInputMessageContentString;
    userInputMessageContext?: UserInputMessageContext;
    userIntent?: UserIntent;
  }
  export type UserInputMessageContentString = string;
  export interface UserInputMessageContext {
    editorState?: EditorState;
    diagnostic?: Diagnostic;
  }
  export type UserIntent = "SUGGEST_ALTERNATE_IMPLEMENTATION"|"APPLY_COMMON_BEST_PRACTICES"|"IMPROVE_CODE"|"SHOW_EXAMPLES"|"CITE_SOURCES"|"EXPLAIN_LINE_BY_LINE"|"EXPLAIN_CODE_SELECTION"|string;
  export interface UserModificationEvent {
    sessionId: UUID;
    requestId: UUID;
    programmingLanguage: ProgrammingLanguage;
    modificationPercentage: Double;
    customizationArn?: CustomizationArn;
    timestamp: Timestamp;
  }
  export interface UserTriggerDecisionEvent {
    sessionId: UUID;
    requestId: UUID;
    customizationArn?: CustomizationArn;
    programmingLanguage: ProgrammingLanguage;
    completionType: CompletionType;
    suggestionState: SuggestionState;
    recommendationLatencyMilliseconds: Double;
    timestamp: Timestamp;
    triggerToResponseLatencyMilliseconds?: Double;
    suggestionReferenceCount?: PrimitiveInteger;
    generatedLine?: PrimitiveInteger;
    numberOfRecommendations?: PrimitiveInteger;
  }
  export interface WorkspaceState {
    uploadId: UploadId;
    programmingLanguage: ProgrammingLanguage;
    contextTruncationScheme?: ContextTruncationScheme;
  }
  /**
   * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
   */
  export type apiVersion = "2022-11-11"|"latest"|string;
  export interface ClientApiVersions {
    /**
     * A string in YYYY-MM-DD format that represents the latest possible API version that can be used in this service. Specify 'latest' to use the latest possible version.
     */
    apiVersion?: apiVersion;
  }
  export type ClientConfiguration = ServiceConfigurationOptions & ClientApiVersions;
  /**
   * Contains interfaces for use with the CodeWhispererUserClient client.
   */
  export import Types = CodeWhispererUserClient;
}
export = CodeWhispererUserClient;

    