version: 0.2

env:
    variables:
        NODE_OPTIONS: '--max-old-space-size=8192'

phases:
    install:
        runtime-versions:
            nodejs: 16

    pre_build:
        commands:
            # Check for implicit env vars passed from the release pipeline.
            - test -n "${TOOLKITS_GITHUB_REPO_OWNER}"
            - test -n "${TARGET_BRANCH}"

    build:
        commands:
            - git clone https://github.com/${TOOLKITS_GITHUB_REPO_OWNER}/aws-toolkit-vscode.git aws-toolkit-vscode
            # checkout the target branch as we want to commit to it later to update versions
            - cd aws-toolkit-vscode && git checkout ${TARGET_BRANCH}

artifacts:
    base-directory: aws-toolkit-vscode
    files:
        - '**/*'
