version: 0.2

phases:
    pre_build:
        commands:
            - aws codeartifact login --tool npm --domain "$TOOLKITS_CODEARTIFACT_DOMAIN" --domain-owner "$TOOLKITS_ACCOUNT_ID" --repository "$TOOLKITS_CODEARTIFACT_REPO"

    install:
        runtime-versions:
            nodejs: 16

    build:
        commands:
            - |
                echo "Removing SNAPSHOT from version string"
                git config --global user.name "aws-toolkit-automation"
                git config --global user.email "<>"
                VERSION=$(node -e "console.log(require('./package.json').version);" | (IFS="-"; read -r version unused && echo "$version"))
                DATE=$(date)
                npm version --no-git-tag-version "$VERSION"
                # Call npm ci because 'createRelease' uses ts-node
                npm ci
            - |
                npm run createRelease
            - |
                git add package.json
                git add package-lock.json
                git commit -m "Release $VERSION"
                echo "tagging commit"
                git tag -a "v$VERSION" -m "version $VERSION $DATE"
                # cleanup
                git clean -fxd
                git reset HEAD --hard

artifacts:
    files:
        - '**/*'
