version: 0.2

env:
    variables:
        NODE_OPTIONS: '--max-old-space-size=8192'

phases:
    install:
        runtime-versions:
            nodejs: 16

    pre_build:
        commands:
            # Check for implicit env vars passed from the release pipeline.
            - test -n "${TOOLKITS_GITHUB_REPO_OWNER}"
            - test -n "${GITHUB_TOKEN}"
            - REPO_URL="https://$GITHUB_TOKEN@github.com/${TOOLKITS_GITHUB_REPO_OWNER}/aws-toolkit-vscode.git"

    build:
        commands:
            - |
                git config --global user.name "aws-toolkit-automation"
                git config --global user.email "<>"
                git remote add originWithCreds "$REPO_URL"
                echo "Adding SNAPSHOT to next version string"
                # Increase minor version
                npm version --no-git-tag-version minor -w packages/toolkit
                VERSION=$(node -e "console.log(require('./packages/toolkit/package.json').version);")
                # Append -SNAPSHOT
                npm version --no-git-tag-version "${VERSION}-SNAPSHOT" -w packages/toolkit
                git add packages/toolkit/package.json
                git add package-lock.json
                git commit -m "Update version to snapshot version: ${VERSION}-SNAPSHOT"
            - |
                if [ "$STAGE" != "prod" ]; then
                  echo "Stage is not production, skipping github push step"
                  exit 0
                fi
                echo "pushing to github"
                git push originWithCreds --tags
                git push originWithCreds master
