#
# Publishes the release vsix to the marketplace.
#

version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20
        commands:
            - apt-get update
            - apt-get install -y libsecret-1-dev

    pre_build:
        commands:
            # Check for implicit env vars passed from the release pipeline.
            - test -n "${VS_MARKETPLACE_PAT}"
            - test -n "${TARGET_EXTENSION}"

    build:
        commands:
            - echo "TARGET_EXTENSION=${TARGET_EXTENSION}"
            # pull in the build artifacts
            - cp -r ${CODEBUILD_SRC_DIR_buildPipeline}/* .
            - |
                UPLOAD_TARGET=$(ls *.vsix)
            - |
                echo "Publishing to vscode marketplace: $UPLOAD_TARGET"
                if [ "$STAGE" != "prod" ]; then
                  echo "skipped (stage=${STAGE})"
                else
                  npx vsce publish --pat "$VS_MARKETPLACE_PAT" --packagePath "$UPLOAD_TARGET"
                fi
            - |
                echo "Publishing to openvsx marketplace: $UPLOAD_TARGET"
                if [ "$STAGE" != "prod" ]; then
                  echo "skipped (stage=${STAGE})"
                else
                  npx --yes ovsx publish "$UPLOAD_TARGET" -p "$OVSX_PAT"
                fi
