#
# Publishes the release vsix to the marketplace.
#

version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - apt-get update
            - apt-get install -y libsecret-1-dev

    pre_build:
        commands:
            # Check for implicit env vars passed from the release pipeline.
            - test -n "${VS_MARKETPLACE_PAT}"
            - test -n "${TARGET_EXTENSION}"

    build:
        commands:
            - echo "TARGET_EXTENSION=${TARGET_EXTENSION}"
            # pull in the build artifacts
            - cp -r ${CODEBUILD_SRC_DIR_buildPipeline}/* .
            - |
                if [ "$STAGE" != "prod" ]; then
                  echo "Stage is not production, skipping publish step"
                  exit 0
                fi
                UPLOAD_TARGET=$(ls *.vsix)
                npx vsce publish --pat "$VS_MARKETPLACE_PAT" --packagePath "$UPLOAD_TARGET"
