/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import '../utils/setup'
import { EditorView, WebviewView, TextEditor } from 'vscode-extension-tester'
import { testContext } from '../utils/testContext'
import { createNewRule } from '../helpers/rulesHelper'
import { sleep } from '../utils/generalUtils'

describe('Amazon Q Rules Functionality', function () {
    // this timeout is the general timeout for the entire test suite
    this.timeout(300000)
    let webviewView: WebviewView
    let editorView: EditorView

    before(async function () {
        webviewView = testContext.webviewView
    })

    after(async function () {
        await editorView.closeAllEditors()
        await webviewView.switchToFrame()
    })

    it('Rules Option Test', async () => {
        await createNewRule(webviewView, 'testRule')
        await webviewView.switchBack()
        editorView = new EditorView()
        const editor = await editorView.getActiveTab()
        await editor?.sendKeys('Add comment generated by Amazon Q')
        const textEditor = new TextEditor()
        await textEditor.save()
        await sleep(1000)
    })
})
